
import Resbar.controladorproducto;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author NERIO
 */
public class agregar_producto_modo_caja extends javax.swing.JFrame {

    /**
     * Creates new form nueva_orden
     */
    
    
      ResultSet rs = null;
    controladorproducto productos = new controladorproducto();
    String seleccionado;
    
    
    public agregar_producto_modo_caja() {
        initComponents();
         this.setIconImage(new ImageIcon(getClass().getResource("/imagenes/imagenrestaurante.png")).getImage());
        this.setTitle("Agregar Productos");
         this.setExtendedState(MAXIMIZED_BOTH);
         bebidas.setVisible(false);
         postres.setVisible(false);
         platos.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnguardar = new javax.swing.JButton();
        btncobrar = new javax.swing.JButton();
        jTextField7 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        btnsalir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btneliminar = new javax.swing.JButton();
        btnagregar = new javax.swing.JButton();
        postres = new org.edisoncor.gui.panel.PanelRound();
        btnpostre1 = new javax.swing.JButton();
        btnpostre2 = new javax.swing.JButton();
        btnpostre3 = new javax.swing.JButton();
        btnpostre4 = new javax.swing.JButton();
        btnpostre5 = new javax.swing.JButton();
        btnpostre6 = new javax.swing.JButton();
        btnpostre7 = new javax.swing.JButton();
        btnpostre8 = new javax.swing.JButton();
        btnpostre9 = new javax.swing.JButton();
        btnpostre10 = new javax.swing.JButton();
        btnpostre11 = new javax.swing.JButton();
        btnpostre12 = new javax.swing.JButton();
        bebidas = new org.edisoncor.gui.panel.PanelRound();
        btnbebida1 = new javax.swing.JButton();
        btnbebida2 = new javax.swing.JButton();
        btnbebida3 = new javax.swing.JButton();
        btnbebida4 = new javax.swing.JButton();
        btnbebida5 = new javax.swing.JButton();
        btnbebida6 = new javax.swing.JButton();
        btnbebida7 = new javax.swing.JButton();
        btnbebida8 = new javax.swing.JButton();
        btnbebida9 = new javax.swing.JButton();
        btnbebida10 = new javax.swing.JButton();
        btnbebida11 = new javax.swing.JButton();
        btnbebida12 = new javax.swing.JButton();
        platos = new org.edisoncor.gui.panel.PanelRound();
        btnplato1 = new javax.swing.JButton();
        btnplato2 = new javax.swing.JButton();
        btnplato3 = new javax.swing.JButton();
        btnplato4 = new javax.swing.JButton();
        btnplato5 = new javax.swing.JButton();
        btnplato6 = new javax.swing.JButton();
        btnplato7 = new javax.swing.JButton();
        btnplato8 = new javax.swing.JButton();
        btnplato9 = new javax.swing.JButton();
        btnplato10 = new javax.swing.JButton();
        btnplato11 = new javax.swing.JButton();
        btnplato12 = new javax.swing.JButton();
        btnplatos = new javax.swing.JButton();
        btnbebidas = new javax.swing.JButton();
        btnpostres = new javax.swing.JButton();
        btnquitar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 0, 0));
        jLabel5.setText("Observaciones");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 150, 120, -1));

        jTextField5.setEditable(false);
        jTextField5.setBackground(new java.awt.Color(0, 255, 204));
        jTextField5.setFocusable(false);
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 640, 130, -1));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("Total:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 640, -1, -1));

        btnguardar.setBackground(new java.awt.Color(102, 255, 102));
        btnguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/save.png"))); // NOI18N
        btnguardar.setText("guardar");
        btnguardar.setBorder(null);
        btnguardar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnguardarMouseMoved(evt);
            }
        });
        btnguardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnguardarMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnguardarMouseEntered(evt);
            }
        });
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 680, 110, 40));

        btncobrar.setBackground(new java.awt.Color(102, 255, 102));
        btncobrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cobro.png"))); // NOI18N
        btncobrar.setText("cobrar");
        btncobrar.setBorder(null);
        btncobrar.setPreferredSize(new java.awt.Dimension(119, 34));
        btncobrar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btncobrarMouseMoved(evt);
            }
        });
        btncobrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btncobrarMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btncobrarMouseEntered(evt);
            }
        });
        btncobrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncobrarActionPerformed(evt);
            }
        });
        jPanel1.add(btncobrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 680, 120, 40));

        jTextField7.setEditable(false);
        jTextField7.setBackground(new java.awt.Color(0, 255, 204));
        jTextField7.setFocusable(false);
        jPanel1.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 110, 60, -1));

        jTextField10.setBackground(new java.awt.Color(0, 255, 204));
        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 140, 350, 70));

        btnsalir.setBackground(new java.awt.Color(102, 255, 102));
        btnsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/dispose.png"))); // NOI18N
        btnsalir.setBorder(null);
        btnsalir.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnsalirMouseMoved(evt);
            }
        });
        btnsalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnsalirMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnsalirMouseEntered(evt);
            }
        });
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 30, 70, 40));

        jLabel2.setBackground(new java.awt.Color(255, 0, 0));
        jLabel2.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setText("Orden:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 110, 70, 20));

        jTable1.setBackground(new java.awt.Color(204, 255, 255));
        jTable1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 0), 2, true));
        jTable1.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jTable1.setForeground(new java.awt.Color(153, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Producto", "Cantidad", "P/c", "Subtotal"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Float.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane2.setViewportView(jTable1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 250, 570, 370));

        btneliminar.setBackground(new java.awt.Color(102, 204, 102));
        btneliminar.setText("-");
        btneliminar.setBorderPainted(false);
        btneliminar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btneliminarMouseMoved(evt);
            }
        });
        btneliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btneliminarMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btneliminarMouseEntered(evt);
            }
        });
        jPanel1.add(btneliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 630, 50, -1));

        btnagregar.setBackground(new java.awt.Color(102, 204, 102));
        btnagregar.setText("+");
        btnagregar.setBorderPainted(false);
        btnagregar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnagregarMouseMoved(evt);
            }
        });
        btnagregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnagregarMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnagregarMouseEntered(evt);
            }
        });
        jPanel1.add(btnagregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 630, 50, -1));

        postres.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnpostre1.setText("Flan");
        postres.add(btnpostre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 400, 90, 90));

        btnpostre2.setText("Budin");
        btnpostre2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpostre2ActionPerformed(evt);
            }
        });
        postres.add(btnpostre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 100, 90));

        btnpostre3.setText("Bollo");
        postres.add(btnpostre3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, 90, 90));

        btnpostre4.setText("Pastel");
        btnpostre4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpostre4ActionPerformed(evt);
            }
        });
        postres.add(btnpostre4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 100, 90));

        btnpostre5.setText("Milhoja");
        postres.add(btnpostre5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 290, 90, 90));

        btnpostre6.setText("cupcake");
        postres.add(btnpostre6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, -1, 90));

        btnpostre7.setText("Gelato");
        btnpostre7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpostre7ActionPerformed(evt);
            }
        });
        postres.add(btnpostre7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 90, 90));

        btnpostre8.setText("Tiramisu");
        postres.add(btnpostre8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, -1, 90));

        btnpostre9.setText("Alfajor");
        postres.add(btnpostre9, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, 90, 90));

        btnpostre10.setText("Crepa");
        postres.add(btnpostre10, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 400, 90, 90));

        btnpostre11.setText("Gelatina");
        btnpostre11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpostre11ActionPerformed(evt);
            }
        });
        postres.add(btnpostre11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 100, 90));

        btnpostre12.setText("Mousse");
        postres.add(btnpostre12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 100, 90));

        jPanel1.add(postres, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 570, 610));

        bebidas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnbebida1.setText("Cafe");
        bebidas.add(btnbebida1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 400, 90, 90));

        btnbebida2.setText("Agua");
        bebidas.add(btnbebida2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 100, 90));

        btnbebida3.setText("Mate");
        bebidas.add(btnbebida3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, 90, 90));

        btnbebida4.setText("Cebada");
        bebidas.add(btnbebida4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 100, 90));

        btnbebida5.setText("Leche");
        bebidas.add(btnbebida5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 290, 90, 90));

        btnbebida6.setText("Licuado");
        bebidas.add(btnbebida6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 100, 90));

        btnbebida7.setText("Te");
        bebidas.add(btnbebida7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 100, 90));

        btnbebida8.setText("Mojito");
        bebidas.add(btnbebida8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 100, 90));

        btnbebida9.setText("Vino");
        bebidas.add(btnbebida9, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, 90, 90));

        btnbebida10.setText("Choco");
        bebidas.add(btnbebida10, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 400, 100, 90));

        btnbebida11.setText("Soda");
        bebidas.add(btnbebida11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 100, 90));

        btnbebida12.setText("Horchata");
        bebidas.add(btnbebida12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, -1, 90));

        jPanel1.add(bebidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 570, 610));

        platos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnplato1.setText("Carne ");
        platos.add(btnplato1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 400, 90, 90));

        btnplato2.setText("Estofado");
        platos.add(btnplato2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, 90));

        btnplato3.setText("Pasta");
        platos.add(btnplato3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, 90, 90));

        btnplato4.setText("Ramen");
        platos.add(btnplato4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 100, 90));

        btnplato5.setText("Flauta");
        platos.add(btnplato5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 290, 90, 90));

        btnplato6.setText("Sopa");
        platos.add(btnplato6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 90, 90));

        btnplato7.setText("Arroz");
        platos.add(btnplato7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 90, 90));

        btnplato8.setText("Pescado");
        platos.add(btnplato8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, -1, 90));

        btnplato9.setText("Guiso");
        platos.add(btnplato9, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, 90, 90));

        btnplato10.setText("Vegetal");
        platos.add(btnplato10, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 400, 90, 90));

        btnplato11.setText("Pollo");
        platos.add(btnplato11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 100, 90));

        btnplato12.setText("Pupusa");
        platos.add(btnplato12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 100, 90));

        jPanel1.add(platos, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 570, 610));

        btnplatos.setText("Platos");
        btnplatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnplatosMouseClicked(evt);
            }
        });
        btnplatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnplatosActionPerformed(evt);
            }
        });
        jPanel1.add(btnplatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 110, -1));

        btnbebidas.setText("Bebidas");
        btnbebidas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnbebidasMouseClicked(evt);
            }
        });
        btnbebidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbebidasActionPerformed(evt);
            }
        });
        jPanel1.add(btnbebidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, -1, -1));

        btnpostres.setText("Postres");
        btnpostres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnpostresMouseClicked(evt);
            }
        });
        btnpostres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpostresActionPerformed(evt);
            }
        });
        jPanel1.add(btnpostres, new org.netbeans.lib.awtextra.AbsoluteConstraints(379, 30, 110, -1));

        btnquitar.setBackground(new java.awt.Color(102, 204, 102));
        btnquitar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_Multiply_32px.png"))); // NOI18N
        btnquitar.setBorderPainted(false);
        btnquitar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnquitarMouseMoved(evt);
            }
        });
        btnquitar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnquitarMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnquitarMouseEntered(evt);
            }
        });
        jPanel1.add(btnquitar, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 630, 50, 25));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 732, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        // TODO add your handling code here:
        dashboard menu=new dashboard();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnsalirActionPerformed

    private void btnsalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsalirMouseEntered
        // TODO add your handling code here:
        btnsalir.setBackground(new Color(0,204,51));//cambia el color del boton cuando paso el puntero sobre el boton
    }//GEN-LAST:event_btnsalirMouseEntered

    private void btnsalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsalirMouseExited
        // TODO add your handling code here:
        btnsalir.setBackground(new Color(102,255,102));//cambia el color del boton cuando paso el puntero sobre el boton
    }//GEN-LAST:event_btnsalirMouseExited

    private void btnsalirMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsalirMouseMoved
        // TODO add your handling code here:
        String texto="Salir";
        btnsalir.setToolTipText(texto);//el metodo setToolTipTex hace que cuando pongo el puntero del raton sobre el boton muestre el nombre del boton
    }//GEN-LAST:event_btnsalirMouseMoved

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void btncobrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncobrarActionPerformed
        // TODO add your handling code here:
        cobrar_orden cobrar=new cobrar_orden();
        cobrar.setVisible(true);
        
    }//GEN-LAST:event_btncobrarActionPerformed

    private void btncobrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncobrarMouseEntered
        // TODO add your handling code here:
        btncobrar.setBackground(new Color(0,204,51));//cambia el color del boton cuando paso el puntero sobre el boton
    }//GEN-LAST:event_btncobrarMouseEntered

    private void btncobrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncobrarMouseExited
        // TODO add your handling code here:
        btncobrar.setBackground(new Color(102,255,102));//cambia el color del boton cuando paso el puntero sobre el boton
    }//GEN-LAST:event_btncobrarMouseExited

    private void btncobrarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncobrarMouseMoved
        // TODO add your handling code here:
        String texto="Cobrar";
        btncobrar.setToolTipText(texto);//el metodo setToolTipTex hace que cuando pongo el puntero del raton sobre el boton muestre el nombre del boton
    }//GEN-LAST:event_btncobrarMouseMoved

    private void btnguardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnguardarMouseEntered
        // TODO add your handling code here:
        btnguardar.setBackground(new Color(0,204,51));//cambia el color del boton cuando paso el puntero sobre el boton
    }//GEN-LAST:event_btnguardarMouseEntered

    private void btnguardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnguardarMouseExited
        // TODO add your handling code here:
        btnguardar.setBackground(new Color(102,255,102));//cambia el color del boton cuando paso el puntero sobre el boton
    }//GEN-LAST:event_btnguardarMouseExited

    private void btnguardarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnguardarMouseMoved
        // TODO add your handling code here:
        String texto="Guardar";
        btnguardar.setToolTipText(texto);//el metodo setToolTipTex hace que cuando pongo el puntero del raton sobre el boton muestre el nombre del boton
    }//GEN-LAST:event_btnguardarMouseMoved

    private void btnagregarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnagregarMouseMoved
        // TODO add your handling code here:
        String texto="Agregar";
btnagregar.setToolTipText(texto);//el metodo setToolTipTex hace que cuando pongo el puntero del raton sobre el boton muestre el nombre del boton
  
    }//GEN-LAST:event_btnagregarMouseMoved

    private void btneliminarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btneliminarMouseMoved
        // TODO add your handling code here:
        String texto="Eliminar";
btneliminar.setToolTipText(texto);//el metodo setToolTipTex hace que cuando pongo el puntero del raton sobre el boton muestre el nombre del boton
  
    }//GEN-LAST:event_btneliminarMouseMoved

    private void btnplatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnplatosMouseClicked
        this.platos.setVisible(true);
        this.bebidas.setVisible(false);
        this.postres.setVisible(false);
    }//GEN-LAST:event_btnplatosMouseClicked

    private void btnplatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnplatosActionPerformed

        rs = null;
    seleccionado="1";//es la categoria platos
        rs = productos.productobyid(seleccionado);
      Vector producto=new Vector(12,5);//se crea un vector de 12 de elemntos con un margen de 5 mas si se sobrepasa el limite de 12
      
        try {
            while (rs.next()) {
                producto.addElement(rs.getString(1));//agregando cada elemento de la consulta al vector productos
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Error", 0);
        }
        
        //aqui se agrega cada elemento del vector a los  botones correspondientes
        btnplato1.setText((String) producto.elementAt(0));
        btnplato2.setText((String) producto.elementAt(1));
        btnplato3.setText((String) producto.elementAt(2));
        btnplato4.setText((String) producto.elementAt(3));
        btnplato5.setText((String) producto.elementAt(4));
        btnplato6.setText((String) producto.elementAt(5));
        btnplato7.setText((String) producto.elementAt(6));
        btnplato8.setText((String) producto.elementAt(7));
        btnplato9.setText((String) producto.elementAt(8));
        btnplato10.setText((String) producto.elementAt(9));
        btnplato11.setText((String) producto.elementAt(10));
        btnplato11.setText((String) producto.elementAt(11));
    }//GEN-LAST:event_btnplatosActionPerformed

    private void btnbebidasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbebidasMouseClicked
        this.bebidas.setVisible(true);
        this.platos.setVisible(false);
        this.postres.setVisible(false);

    }//GEN-LAST:event_btnbebidasMouseClicked

    private void btnbebidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbebidasActionPerformed

        rs = null;
    seleccionado="2";//es la categoria bebidas
        rs = productos.productobyid(seleccionado);
      Vector producto=new Vector(12,5);//se crea un vector de 12 de elemntos con un margen de 5 mas si se sobrepasa el limite de 12
      
        try {
            while (rs.next()) {
                producto.addElement(rs.getString(1));//agregando cada elemento de la consulta al vector productos
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Error", 0);
        }
        
        //aqui se agrega cada elemento del vector a los  botones correspondientes
        btnbebida1.setText((String) producto.elementAt(0));
        btnbebida2.setText((String) producto.elementAt(1));
        btnbebida3.setText((String) producto.elementAt(2));
        btnbebida4.setText((String) producto.elementAt(3));
        btnbebida5.setText((String) producto.elementAt(4));
        btnbebida6.setText((String) producto.elementAt(5));
        btnbebida7.setText((String) producto.elementAt(6));
        btnbebida8.setText((String) producto.elementAt(7));
        btnbebida9.setText((String) producto.elementAt(8));
        btnbebida10.setText((String) producto.elementAt(9));
        btnbebida11.setText((String) producto.elementAt(10));
        btnbebida12.setText((String) producto.elementAt(11));
    }//GEN-LAST:event_btnbebidasActionPerformed

    private void btnpostresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnpostresMouseClicked
        // TODO add your handling code here:
        this.bebidas.setVisible(false);
        this.platos.setVisible(false);
        this.postres.setVisible(true);
    }//GEN-LAST:event_btnpostresMouseClicked

    private void btnpostresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpostresActionPerformed


         rs = null;
    seleccionado="3";//es la categoria postres
        rs = productos.productobyid(seleccionado);
      Vector producto=new Vector(12,5);//se crea un vector de 12 de elemntos con un margen de 5 mas si se sobrepasa el limite de 12
      
        try {
            while (rs.next()) {
                producto.addElement(rs.getString(1));//agregando cada elemento de la consulta al vector productos
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Error", 0);
        }
        
        //aqui se agrega cada elemento del vector a los  botones correspondientes
        btnpostre1.setText((String) producto.elementAt(0));
        btnpostre2.setText((String) producto.elementAt(1));
        btnpostre3.setText((String) producto.elementAt(2));
        btnpostre4.setText((String) producto.elementAt(3));
        btnpostre5.setText((String) producto.elementAt(4));
        btnpostre6.setText((String) producto.elementAt(5));
        btnpostre7.setText((String) producto.elementAt(6));
        btnpostre8.setText((String) producto.elementAt(7));
        btnpostre9.setText((String) producto.elementAt(8));
        btnpostre10.setText((String) producto.elementAt(9));
        btnpostre11.setText((String) producto.elementAt(10));
        btnpostre11.setText((String) producto.elementAt(11));
    }//GEN-LAST:event_btnpostresActionPerformed

    private void btnquitarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnquitarMouseMoved
        // TODO add your handling code here:
        String texto="Quitar";
        btnquitar.setToolTipText(texto);//el metodo setToolTipTex hace que cuando pongo el puntero del raton sobre el boton muestre el nombre del boton
  
    }//GEN-LAST:event_btnquitarMouseMoved

    private void btneliminarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btneliminarMouseEntered
        // TODO add your handling code here:
        btneliminar.setBackground(new Color(0,255,102));//cambia el color del boton cuando paso el puntero sobre el boton
    }//GEN-LAST:event_btneliminarMouseEntered

    private void btneliminarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btneliminarMouseExited
        // TODO add your handling code here:
        btneliminar.setBackground(new Color(102,204,102));//cambia el color del boton cuando paso el puntero sobre el boton
    }//GEN-LAST:event_btneliminarMouseExited

    private void btnagregarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnagregarMouseEntered
        // TODO add your handling code here:
        btnagregar.setBackground(new Color(0,255,102));//cambia el color del boton cuando paso el puntero sobre el boton
    }//GEN-LAST:event_btnagregarMouseEntered

    private void btnagregarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnagregarMouseExited
        // TODO add your handling code here:
        btnagregar.setBackground(new Color(102,204,102));//cambia el color del boton cuando paso el puntero sobre el boton
    }//GEN-LAST:event_btnagregarMouseExited

    private void btnquitarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnquitarMouseEntered
        // TODO add your handling code here:
        btnquitar.setBackground(new Color(0,255,102));//cambia el color del boton cuando paso el puntero sobre el boton
    }//GEN-LAST:event_btnquitarMouseEntered

    private void btnquitarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnquitarMouseExited
        // TODO add your handling code here:
        btnquitar.setBackground(new Color(102,204,102));//cambia el color del boton cuando paso el puntero sobre el boton
    }//GEN-LAST:event_btnquitarMouseExited

    private void btnpostre11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpostre11ActionPerformed

        

       
    }//GEN-LAST:event_btnpostre11ActionPerformed

    private void btnpostre2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpostre2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnpostre2ActionPerformed

    private void btnpostre7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpostre7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnpostre7ActionPerformed

    private void btnpostre4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpostre4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnpostre4ActionPerformed

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnguardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(agregar_producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(agregar_producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(agregar_producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(agregar_producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new agregar_producto("0").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.panel.PanelRound bebidas;
    private javax.swing.JButton btnagregar;
    private javax.swing.JButton btnbebida1;
    private javax.swing.JButton btnbebida10;
    private javax.swing.JButton btnbebida11;
    private javax.swing.JButton btnbebida12;
    private javax.swing.JButton btnbebida2;
    private javax.swing.JButton btnbebida3;
    private javax.swing.JButton btnbebida4;
    private javax.swing.JButton btnbebida5;
    private javax.swing.JButton btnbebida6;
    private javax.swing.JButton btnbebida7;
    private javax.swing.JButton btnbebida8;
    private javax.swing.JButton btnbebida9;
    private javax.swing.JButton btnbebidas;
    private javax.swing.JButton btncobrar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnplato1;
    private javax.swing.JButton btnplato10;
    private javax.swing.JButton btnplato11;
    private javax.swing.JButton btnplato12;
    private javax.swing.JButton btnplato2;
    private javax.swing.JButton btnplato3;
    private javax.swing.JButton btnplato4;
    private javax.swing.JButton btnplato5;
    private javax.swing.JButton btnplato6;
    private javax.swing.JButton btnplato7;
    private javax.swing.JButton btnplato8;
    private javax.swing.JButton btnplato9;
    private javax.swing.JButton btnplatos;
    private javax.swing.JButton btnpostre1;
    private javax.swing.JButton btnpostre10;
    private javax.swing.JButton btnpostre11;
    private javax.swing.JButton btnpostre12;
    private javax.swing.JButton btnpostre2;
    private javax.swing.JButton btnpostre3;
    private javax.swing.JButton btnpostre4;
    private javax.swing.JButton btnpostre5;
    private javax.swing.JButton btnpostre6;
    private javax.swing.JButton btnpostre7;
    private javax.swing.JButton btnpostre8;
    private javax.swing.JButton btnpostre9;
    private javax.swing.JButton btnpostres;
    private javax.swing.JButton btnquitar;
    private javax.swing.JButton btnsalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField7;
    private org.edisoncor.gui.panel.PanelRound platos;
    private org.edisoncor.gui.panel.PanelRound postres;
    // End of variables declaration//GEN-END:variables
}
