package Resbar;


import Modelo.Ordenes;
import Resbar.ControladorAgregarOrden;
import Resbar.controladorproducto;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author NERIO
 */
public class modificar_orden extends javax.swing.JFrame {

    /**
     * Creates new form detalle
     */
    
     private String fechaActual="2019-06-18 00:00:00";
    
    DefaultTableModel modeloModificarOrden = new DefaultTableModel(){
    
      @Override
         public boolean isCellEditable(int fila, int columna) {
            if(columna==4){
            return true;
            }else{
            return false;
            }
         }
    };
    ResultSet rs = null;
    controladorproducto productos = new controladorproducto();
    //String IdOrden;
    String seleccionado;
    
    
    private void sumarcelda(){
    double sumarcolumna=0;
    for(int i=0;i<tblModificarOrden.getRowCount();i++){
    sumarcolumna=sumarcolumna+Double.parseDouble(modeloModificarOrden.getValueAt(i,3).toString());
    txtTotal.setText(String.valueOf(sumarcolumna));
    }
    }
    
    public modificar_orden(int id,String mesa,String mesero,String cliente,String observacion) {
        initComponents();
        
        
        
        this.txtIdOrden.setText(Integer.toString(id));
        this.txtmesa.setText(mesa);
        this.txtmesero.setText(mesero);
        this.txtcliente.setText(cliente);
        this.txtobservacion.setText(observacion);
         this.setIconImage(new ImageIcon(getClass().getResource("/imagenes/imagenrestaurante.png")).getImage());
        this.setTitle("Modificar Orden");
        this.setLocationRelativeTo(null);
         String Id=this.txtIdOrden.getText();
        llenar(Id);
        sumarcelda();
    }
        

//    modificar_orden(String toString) {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
//    }
//
//    modificar_orden(String toString) {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
//    }

   // String Id=this.txtIdOrden.getText();
    
     private void llenar(String Id){
    
       rs=null;
        rs = productos.findByIdOrden(Id);
       //le pone el nombre  a las columnas en la tabla
        modeloModificarOrden.addColumn("Producto");
        modeloModificarOrden.addColumn("Cantidad");
        modeloModificarOrden.addColumn("P/u");
        modeloModificarOrden.addColumn("Subtotal");
        String[] dato=new String[4];
        
        try {
            while (rs.next()) {
                dato[0]=rs.getString(1);
                dato[1]=rs.getString(2);
                dato[2]=rs.getString(3);
                dato[3]=rs.getString(3);
                modeloModificarOrden.addRow(dato);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Error", 0);
        }
        tblModificarOrden.setModel(modeloModificarOrden);
    
    
    
    }
    
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblModificarOrden = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtIdOrden = new javax.swing.JTextField();
        txtmesa = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtobservacion = new javax.swing.JTextField();
        txtcliente = new javax.swing.JTextField();
        txtmesero = new javax.swing.JTextField();
        btnguardar = new javax.swing.JButton();
        btnsalir = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        btnagregar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblModificarOrden.setBackground(new java.awt.Color(204, 255, 255));
        tblModificarOrden.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 0), 2, true));
        tblModificarOrden.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        tblModificarOrden.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Producto", "Cantidad", "P/u", "Subtotal"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Float.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblModificarOrden.setToolTipText("Ordenes");
        tblModificarOrden.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane2.setViewportView(tblModificarOrden);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 183, 570, 305));

        jLabel2.setBackground(new java.awt.Color(255, 0, 0));
        jLabel2.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setText("Orden:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 70, 20));

        txtIdOrden.setEditable(false);
        txtIdOrden.setBackground(new java.awt.Color(0, 255, 204));
        txtIdOrden.setFocusable(false);
        jPanel1.add(txtIdOrden, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 60, -1));

        txtmesa.setEditable(false);
        txtmesa.setBackground(new java.awt.Color(0, 255, 204));
        jPanel1.add(txtmesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 60, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 0));
        jLabel3.setText("Mesa:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 50, 20));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 0, 0));
        jLabel6.setText("Mesero:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 0));
        jLabel4.setText("Cliente:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 70, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 0, 0));
        jLabel5.setText("Observacion:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 110, -1));

        txtobservacion.setBackground(new java.awt.Color(0, 255, 204));
        txtobservacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtobservacionActionPerformed(evt);
            }
        });
        jPanel1.add(txtobservacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, 390, 50));

        txtcliente.setEditable(false);
        txtcliente.setBackground(new java.awt.Color(0, 255, 204));
        jPanel1.add(txtcliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, 390, -1));

        txtmesero.setEditable(false);
        txtmesero.setBackground(new java.awt.Color(0, 255, 204));
        txtmesero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmeseroActionPerformed(evt);
            }
        });
        jPanel1.add(txtmesero, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 60, 220, -1));

        btnguardar.setBackground(new java.awt.Color(102, 255, 102));
        btnguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/save.png"))); // NOI18N
        btnguardar.setText("Guardar");
        btnguardar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnguardarMouseMoved(evt);
            }
        });
        btnguardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnguardarMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnguardarMouseEntered(evt);
            }
        });
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(429, 524, -1, -1));

        btnsalir.setBackground(new java.awt.Color(102, 255, 102));
        btnsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/dispose.png"))); // NOI18N
        btnsalir.setBorder(null);
        btnsalir.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnsalirMouseMoved(evt);
            }
        });
        btnsalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnsalirMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnsalirMouseEntered(evt);
            }
        });
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(828, 12, 70, 40));

        btneliminar.setBackground(new java.awt.Color(102, 204, 103));
        btneliminar.setText("-");
        btneliminar.setBorderPainted(false);
        btneliminar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btneliminarMouseMoved(evt);
            }
        });
        btneliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btneliminarMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btneliminarMouseEntered(evt);
            }
        });
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btneliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 490, 50, -1));

        btnagregar.setBackground(new java.awt.Color(102, 204, 102));
        btnagregar.setText("+");
        btnagregar.setBorderPainted(false);
        btnagregar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnagregarMouseMoved(evt);
            }
        });
        btnagregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnagregarMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnagregarMouseEntered(evt);
            }
        });
        btnagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregarActionPerformed(evt);
            }
        });
        jPanel1.add(btnagregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 490, 50, -1));

        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("Total:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 500, -1, -1));

        txtTotal.setEditable(false);
        txtTotal.setBackground(new java.awt.Color(0, 255, 204));
        jPanel1.add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 500, 110, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtobservacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtobservacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtobservacionActionPerformed

    private void txtmeseroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmeseroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmeseroActionPerformed

    private void btnguardarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnguardarMouseMoved
        // TODO add your handling code here:
         String texto="Guardar";
btnguardar.setToolTipText(texto);//el metodo setToolTipTex hace que cuando pongo el puntero del raton sobre el boton muestre el nombre del boton
  
    }//GEN-LAST:event_btnguardarMouseMoved

    private void btnguardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnguardarMouseEntered
        // TODO add your handling code here:
           btnguardar.setBackground(new Color(0,204,51));//cambia el color del boton cuando paso el puntero sobre el boton
   
    }//GEN-LAST:event_btnguardarMouseEntered

    private void btnguardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnguardarMouseExited
        // TODO add your handling code here:
         btnguardar.setBackground(new Color(102,255,102));//cambia el color del boton cuando paso el puntero sobre el boton
   
    }//GEN-LAST:event_btnguardarMouseExited

    private void btnsalirMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsalirMouseMoved
        // TODO add your handling code here:
        String texto="Salir";
        btnsalir.setToolTipText(texto);//el metodo setToolTipTex hace que cuando pongo el puntero del raton sobre el boton muestre el nombre del boton

    }//GEN-LAST:event_btnsalirMouseMoved

    private void btnsalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsalirMouseExited
        // TODO add your handling code here:
        btnsalir.setBackground(new Color(102,255,102));//cambia el color del boton cuando paso el puntero sobre el boton

    }//GEN-LAST:event_btnsalirMouseExited

    private void btnsalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsalirMouseEntered
        // TODO add your handling code here:
        btnsalir.setBackground(new Color(0,204,51));//cambia el color del boton cuando paso el puntero sobre el boton

    }//GEN-LAST:event_btnsalirMouseEntered

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        // TODO add your handling code here:
       // dashboard menu=new dashboard();
        //menu.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnsalirActionPerformed

    private void btneliminarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btneliminarMouseMoved
        // TODO add your handling code here:
        String texto="Eliminar";
btneliminar.setToolTipText(texto);//el metodo setToolTipTex hace que cuando pongo el puntero del raton sobre el boton muestre el nombre del boton
  
    }//GEN-LAST:event_btneliminarMouseMoved

    private void btnagregarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnagregarMouseMoved
        // TODO add your handling code here:
        String texto="Agregar";
btnagregar.setToolTipText(texto);//el metodo setToolTipTex hace que cuando pongo el puntero del raton sobre el boton muestre el nombre del boton
  
    }//GEN-LAST:event_btnagregarMouseMoved

    private void btneliminarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btneliminarMouseEntered
        // TODO add your handling code here:
        btneliminar.setBackground(new Color(0,255,102));//cambia el color del boton cuando paso el puntero sobre el boton
    }//GEN-LAST:event_btneliminarMouseEntered

    private void btneliminarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btneliminarMouseExited
        // TODO add your handling code here:
        btneliminar.setBackground(new Color(102,204,102));//cambia el color del boton cuando paso el puntero sobre el boton
    }//GEN-LAST:event_btneliminarMouseExited

    private void btnagregarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnagregarMouseEntered
        // TODO add your handling code here:
        btnagregar.setBackground(new Color(0,255,102));//cambia el color del boton cuando paso el puntero sobre el boton
    }//GEN-LAST:event_btnagregarMouseEntered

    private void btnagregarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnagregarMouseExited
        // TODO add your handling code here:
        btnagregar.setBackground(new Color(102,204,102));//cambia el color del boton cuando paso el puntero sobre el boton
    }//GEN-LAST:event_btnagregarMouseExited

    
//    double subtotal=1;
     double total1=0;
    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
       
 if (tblModificarOrden.getSelectedRow() != -1) //saber si esta seleccionada la fila en la tabla
            
        {
           
           
           String nombre=modeloModificarOrden.getValueAt(tblModificarOrden.getSelectedRow(), 0).toString(); 
           int cantidad=Integer.parseInt(modeloModificarOrden.getValueAt(tblModificarOrden.getSelectedRow(), 1).toString());
           double precio=Double.parseDouble(modeloModificarOrden.getValueAt(tblModificarOrden.getSelectedRow(), 2).toString());

           int IdOrden=Integer.parseInt(txtIdOrden.getText());
           
           String observacion=txtobservacion.getText();
           
           
           total1=Double.parseDouble(txtTotal.getText().toString());
          
           
          
           
           productos.ModificarOrden(total1, cantidad, observacion, nombre, IdOrden);
           
           JOptionPane.showMessageDialog(null,"Modificacion exitosa");
           
         
       
            
 } else {
             
             JOptionPane.showMessageDialog(null, "Seleccione una Orden,para modificar", null, JOptionPane.WARNING_MESSAGE);
            
        }
 
 dispose();



        
        
        
        
        
        
        
    }//GEN-LAST:event_btnguardarActionPerformed

    
    
    
    
    
    
    
    
    
    
    
    
    
    
    double subtotal=1;
    double total=0;
    int estatico=1;
    private void btnagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregarActionPerformed
        // TODO add your handling code here:
        
         if (tblModificarOrden.getSelectedRow() != -1) //saber si esta seleccionada la fila en la tabla
            
        {
//            int cantidad=Integer.parseInt(modeloorden.getValueAt(tblordenes.getSelectedRow(), 1).toString());//mando la informacion de la fila a los txt donde se editara la informacion en este caso para el id
//          cantidad=cantidad+1;
           //dato[1]=""+cantidad;
            
          String valor=String.valueOf(tblModificarOrden.getValueAt(tblModificarOrden.getSelectedRow(), 1));
          int Nvalor=Integer.parseInt(valor)+estatico;
         tblModificarOrden.setValueAt(Nvalor,tblModificarOrden.getSelectedRow(), 1);
         
         int cantidad=Integer.parseInt(modeloModificarOrden.getValueAt(tblModificarOrden.getSelectedRow(), 1).toString());
           double precio=Double.parseDouble(modeloModificarOrden.getValueAt(tblModificarOrden.getSelectedRow(), 2).toString());
         
          double subtotal=precio*cantidad;
           
           double total=subtotal;
           
           tblModificarOrden.setValueAt(subtotal,tblModificarOrden.getSelectedRow(), 3);
           
         
           
           
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione un elemento para agregar o eliminar productos", null, JOptionPane.WARNING_MESSAGE);
         } 

        
        sumarcelda();
        
        
        
    }//GEN-LAST:event_btnagregarActionPerformed
 int estatico2=1;
//  double subtotal2=1;
//    double total2=0;
    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        // TODO add your handling code here:
         if (tblModificarOrden.getSelectedRow() != -1) //saber si esta seleccionada la fila en la tabla
            
        {
            String valor=String.valueOf(tblModificarOrden.getValueAt(tblModificarOrden.getSelectedRow(), 1));
         int Nvalor=Integer.parseInt(valor);
            if(Nvalor>1){

          valor=String.valueOf(tblModificarOrden.getValueAt(tblModificarOrden.getSelectedRow(), 1));
          Nvalor=Integer.parseInt(valor)-estatico;
           tblModificarOrden.setValueAt(Nvalor,tblModificarOrden.getSelectedRow(), 1);
            
           
           int cantidad=Integer.parseInt(modeloModificarOrden.getValueAt(tblModificarOrden.getSelectedRow(), 1).toString());
           double precio=Double.parseDouble(modeloModificarOrden.getValueAt(tblModificarOrden.getSelectedRow(), 2).toString());
         
          double subtotal=precio*cantidad;
           
           double total=subtotal;
           tblModificarOrden.setValueAt(subtotal,tblModificarOrden.getSelectedRow(), 3);
            

            
            }else{
                JOptionPane.showMessageDialog(null, "No se puede eliminar cantidades iguales a uno");
        } 
            
        }
        else {
            JOptionPane.showMessageDialog(null, "Seleccione un elemento para agregar o eliminar productos", null, JOptionPane.WARNING_MESSAGE);
         }

        
        
        
        sumarcelda();
        
        
        
    }//GEN-LAST:event_btneliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(modificar_orden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(modificar_orden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(modificar_orden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(modificar_orden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new modificar_orden(0,"0","0","0","").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnagregar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnsalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblModificarOrden;
    private javax.swing.JTextField txtIdOrden;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtcliente;
    private javax.swing.JTextField txtmesa;
    private javax.swing.JTextField txtmesero;
    private javax.swing.JTextField txtobservacion;
    // End of variables declaration//GEN-END:variables
}
