
import java.awt.Color;
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author NERIO
 */
public class nueva_orden_modo_caja extends javax.swing.JFrame {

    /**
     * Creates new form nueva_orden
     */
    public nueva_orden_modo_caja() {
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("/imagenes/imagenrestaurante.png")).getImage());
        this.setTitle("Nueva Orden");
         this.setExtendedState(MAXIMIZED_BOTH);
         bebidas.setVisible(false);
         postres.setVisible(false);
         platos.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnguardar = new javax.swing.JButton();
        btncobrar = new javax.swing.JButton();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        btnsalir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btneliminar = new javax.swing.JButton();
        btnagregar = new javax.swing.JButton();
        postres = new org.edisoncor.gui.panel.PanelRound();
        jButton39 = new javax.swing.JButton();
        jButton40 = new javax.swing.JButton();
        jButton41 = new javax.swing.JButton();
        jButton42 = new javax.swing.JButton();
        jButton43 = new javax.swing.JButton();
        jButton44 = new javax.swing.JButton();
        jButton45 = new javax.swing.JButton();
        jButton46 = new javax.swing.JButton();
        jButton47 = new javax.swing.JButton();
        jButton48 = new javax.swing.JButton();
        jButton49 = new javax.swing.JButton();
        jButton50 = new javax.swing.JButton();
        bebidas = new org.edisoncor.gui.panel.PanelRound();
        jButton51 = new javax.swing.JButton();
        jButton52 = new javax.swing.JButton();
        jButton53 = new javax.swing.JButton();
        jButton54 = new javax.swing.JButton();
        jButton55 = new javax.swing.JButton();
        jButton56 = new javax.swing.JButton();
        jButton57 = new javax.swing.JButton();
        jButton58 = new javax.swing.JButton();
        jButton59 = new javax.swing.JButton();
        jButton60 = new javax.swing.JButton();
        jButton61 = new javax.swing.JButton();
        jButton62 = new javax.swing.JButton();
        platos = new org.edisoncor.gui.panel.PanelRound();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 0, 0));
        jLabel5.setText("Observacion");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 210, 120, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 0, 0));
        jLabel6.setText("Mesero:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 150, -1, -1));

        jTextField5.setEditable(false);
        jTextField5.setBackground(new java.awt.Color(0, 255, 204));
        jTextField5.setFocusable(false);
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 650, 130, -1));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("Total:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 650, -1, -1));

        btnguardar.setBackground(new java.awt.Color(102, 255, 102));
        btnguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/save.png"))); // NOI18N
        btnguardar.setText("guardar");
        btnguardar.setBorder(null);
        btnguardar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnguardarMouseMoved(evt);
            }
        });
        btnguardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnguardarMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnguardarMouseEntered(evt);
            }
        });
        jPanel1.add(btnguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 690, 110, 40));

        btncobrar.setBackground(new java.awt.Color(102, 255, 102));
        btncobrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cobro.png"))); // NOI18N
        btncobrar.setText("cobrar");
        btncobrar.setBorder(null);
        btncobrar.setPreferredSize(new java.awt.Dimension(119, 34));
        btncobrar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btncobrarMouseMoved(evt);
            }
        });
        btncobrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btncobrarMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btncobrarMouseEntered(evt);
            }
        });
        btncobrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncobrarActionPerformed(evt);
            }
        });
        jPanel1.add(btncobrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 690, 120, 40));

        jTextField7.setEditable(false);
        jTextField7.setBackground(new java.awt.Color(0, 255, 204));
        jTextField7.setFocusable(false);
        jPanel1.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 110, 60, -1));

        jTextField8.setBackground(new java.awt.Color(0, 255, 204));
        jPanel1.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 150, 60, -1));

        jTextField9.setBackground(new java.awt.Color(0, 255, 204));
        jPanel1.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 180, 390, -1));

        jTextField10.setBackground(new java.awt.Color(0, 255, 204));
        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 210, 390, 50));

        jTextField11.setBackground(new java.awt.Color(0, 255, 204));
        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 150, 250, -1));

        btnsalir.setBackground(new java.awt.Color(102, 255, 102));
        btnsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/dispose.png"))); // NOI18N
        btnsalir.setBorder(null);
        btnsalir.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnsalirMouseMoved(evt);
            }
        });
        btnsalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnsalirMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnsalirMouseEntered(evt);
            }
        });
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 30, 70, 40));

        jLabel2.setBackground(new java.awt.Color(255, 0, 0));
        jLabel2.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setText("Orden:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 110, 70, 20));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 0));
        jLabel3.setText("Mesa:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 150, 50, 20));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 0));
        jLabel4.setText("Cliente:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 180, 70, -1));

        jTable1.setBackground(new java.awt.Color(204, 255, 255));
        jTable1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 0), 2, true));
        jTable1.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jTable1.setForeground(new java.awt.Color(153, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Productos", "Cantidad", "P/c", "Subtotal"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class, java.lang.Float.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane2.setViewportView(jTable1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 270, 570, 370));

        btneliminar.setBackground(new java.awt.Color(102, 204, 102));
        btneliminar.setText("-");
        btneliminar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btneliminarMouseMoved(evt);
            }
        });
        jPanel1.add(btneliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 650, 50, -1));

        btnagregar.setBackground(new java.awt.Color(102, 204, 102));
        btnagregar.setText("+");
        btnagregar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnagregarMouseMoved(evt);
            }
        });
        jPanel1.add(btnagregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 650, 50, -1));

        postres.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton39.setText("Flan");
        postres.add(jButton39, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 400, 90, 90));

        jButton40.setText("Budin");
        postres.add(jButton40, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 100, 90));

        jButton41.setText("Bollo");
        postres.add(jButton41, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, 90, 90));

        jButton42.setText("Pastel");
        postres.add(jButton42, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 100, 90));

        jButton43.setText("Milhoja");
        postres.add(jButton43, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 290, 90, 90));

        jButton44.setText("cupcake");
        postres.add(jButton44, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, -1, 90));

        jButton45.setText("Gelato");
        postres.add(jButton45, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 90, 90));

        jButton46.setText("Tiramisu");
        postres.add(jButton46, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, -1, 90));

        jButton47.setText("Alfajor");
        postres.add(jButton47, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, 90, 90));

        jButton48.setText("Crepa");
        postres.add(jButton48, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 400, 90, 90));

        jButton49.setText("Gelatina");
        postres.add(jButton49, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 100, 90));

        jButton50.setText("Mousse");
        postres.add(jButton50, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 100, 90));

        jPanel1.add(postres, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 570, 610));

        bebidas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton51.setText("Cafe");
        bebidas.add(jButton51, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 400, 90, 90));

        jButton52.setText("Agua");
        bebidas.add(jButton52, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 100, 90));

        jButton53.setText("Mate");
        bebidas.add(jButton53, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, 90, 90));

        jButton54.setText("Cebada");
        bebidas.add(jButton54, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 100, 90));

        jButton55.setText("Leche");
        bebidas.add(jButton55, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 290, 90, 90));

        jButton56.setText("Licuado");
        bebidas.add(jButton56, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 100, 90));

        jButton57.setText("Te");
        bebidas.add(jButton57, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 100, 90));

        jButton58.setText("Mojito");
        bebidas.add(jButton58, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 100, 90));

        jButton59.setText("Vino");
        bebidas.add(jButton59, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, 90, 90));

        jButton60.setText("Choco");
        bebidas.add(jButton60, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 400, 100, 90));

        jButton61.setText("Soda");
        bebidas.add(jButton61, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 100, 90));

        jButton62.setText("Horchata");
        bebidas.add(jButton62, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, -1, 90));

        jPanel1.add(bebidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 570, 610));

        platos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton27.setText("Carne ");
        platos.add(jButton27, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 400, 90, 90));

        jButton28.setText("Estofado");
        platos.add(jButton28, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, 90));

        jButton29.setText("Pasta");
        platos.add(jButton29, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, 90, 90));

        jButton30.setText("Ramen");
        platos.add(jButton30, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 100, 90));

        jButton31.setText("Flauta");
        platos.add(jButton31, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 290, 90, 90));

        jButton32.setText("Sopa");
        platos.add(jButton32, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 90, 90));

        jButton33.setText("Arroz");
        platos.add(jButton33, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 90, 90));

        jButton34.setText("Pescado");
        platos.add(jButton34, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, -1, 90));

        jButton35.setText("Guiso");
        platos.add(jButton35, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, 90, 90));

        jButton36.setText("Vegetal");
        platos.add(jButton36, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 400, 90, 90));

        jButton37.setText("Pollo");
        platos.add(jButton37, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 100, 90));

        jButton38.setText("Pupusa");
        platos.add(jButton38, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 100, 90));

        jPanel1.add(platos, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 570, 610));

        jButton1.setText("Platos");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 110, -1));

        jButton2.setText("Bebidas");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, -1, -1));

        jButton3.setText("Postres");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(379, 30, 110, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1383, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 767, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        // TODO add your handling code here:
        dashboard menu=new dashboard();
        menu.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnsalirActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void btncobrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncobrarActionPerformed
        // TODO add your handling code here:
        cobrar_orden cobrar=new cobrar_orden();
        cobrar.setVisible(true);
        
    }//GEN-LAST:event_btncobrarActionPerformed

    private void btnguardarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnguardarMouseMoved
        // TODO add your handling code here:
         String texto="Guardar";
btnguardar.setToolTipText(texto);//el metodo setToolTipTex hace que cuando pongo el puntero del raton sobre el boton muestre el nombre del boton
  
    }//GEN-LAST:event_btnguardarMouseMoved

    private void btncobrarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncobrarMouseMoved
        // TODO add your handling code here:
         String texto="Cobrar";
btncobrar.setToolTipText(texto);//el metodo setToolTipTex hace que cuando pongo el puntero del raton sobre el boton muestre el nombre del boton
  
    }//GEN-LAST:event_btncobrarMouseMoved

    private void btnsalirMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsalirMouseMoved
        // TODO add your handling code here:
         String texto="Salir";
btnsalir.setToolTipText(texto);//el metodo setToolTipTex hace que cuando pongo el puntero del raton sobre el boton muestre el nombre del boton
  
    }//GEN-LAST:event_btnsalirMouseMoved

    private void btnguardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnguardarMouseEntered
        // TODO add your handling code here:
         btnguardar.setBackground(new Color(0,204,51));//cambia el color del boton cuando paso el puntero sobre el boton
   
    }//GEN-LAST:event_btnguardarMouseEntered

    private void btnguardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnguardarMouseExited
        // TODO add your handling code here:
         btnguardar.setBackground(new Color(102,255,102));//cambia el color del boton cuando paso el puntero sobre el boton
   
    }//GEN-LAST:event_btnguardarMouseExited

    private void btncobrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncobrarMouseEntered
        // TODO add your handling code here:
         btncobrar.setBackground(new Color(0,204,51));//cambia el color del boton cuando paso el puntero sobre el boton
   
    }//GEN-LAST:event_btncobrarMouseEntered

    private void btncobrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncobrarMouseExited
        // TODO add your handling code here:
         btncobrar.setBackground(new Color(102,255,102));//cambia el color del boton cuando paso el puntero sobre el boton
   
    }//GEN-LAST:event_btncobrarMouseExited

    private void btnsalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsalirMouseEntered
        // TODO add your handling code here:
         btnsalir.setBackground(new Color(0,204,51));//cambia el color del boton cuando paso el puntero sobre el boton
   
    }//GEN-LAST:event_btnsalirMouseEntered

    private void btnsalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsalirMouseExited
        // TODO add your handling code here:
         btnsalir.setBackground(new Color(102,255,102));//cambia el color del boton cuando paso el puntero sobre el boton
   
    }//GEN-LAST:event_btnsalirMouseExited

    private void btnagregarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnagregarMouseMoved
        // TODO add your handling code here:
         String texto="Agregar";
btnagregar.setToolTipText(texto);//el metodo setToolTipTex hace que cuando pongo el puntero del raton sobre el boton muestre el nombre del boton
  
    }//GEN-LAST:event_btnagregarMouseMoved

    private void btneliminarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btneliminarMouseMoved
        // TODO add your handling code here:
         String texto="Eliminar";
btneliminar.setToolTipText(texto);//el metodo setToolTipTex hace que cuando pongo el puntero del raton sobre el boton muestre el nombre del boton
  
    }//GEN-LAST:event_btneliminarMouseMoved

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        this.platos.setVisible(true);
        this.bebidas.setVisible(false);
        this.postres.setVisible(false);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        this.bebidas.setVisible(true);
        this.platos.setVisible(false);
        this.postres.setVisible(false);

    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        this.bebidas.setVisible(false);
        this.platos.setVisible(false);
        this.postres.setVisible(true);
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(agregar_producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(agregar_producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(agregar_producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(agregar_producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new agregar_producto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.panel.PanelRound bebidas;
    private javax.swing.JButton btnagregar;
    private javax.swing.JButton btncobrar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnsalir;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton42;
    private javax.swing.JButton jButton43;
    private javax.swing.JButton jButton44;
    private javax.swing.JButton jButton45;
    private javax.swing.JButton jButton46;
    private javax.swing.JButton jButton47;
    private javax.swing.JButton jButton48;
    private javax.swing.JButton jButton49;
    private javax.swing.JButton jButton50;
    private javax.swing.JButton jButton51;
    private javax.swing.JButton jButton52;
    private javax.swing.JButton jButton53;
    private javax.swing.JButton jButton54;
    private javax.swing.JButton jButton55;
    private javax.swing.JButton jButton56;
    private javax.swing.JButton jButton57;
    private javax.swing.JButton jButton58;
    private javax.swing.JButton jButton59;
    private javax.swing.JButton jButton60;
    private javax.swing.JButton jButton61;
    private javax.swing.JButton jButton62;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private org.edisoncor.gui.panel.PanelRound platos;
    private org.edisoncor.gui.panel.PanelRound postres;
    // End of variables declaration//GEN-END:variables
}
