
import Modelo.Ordenes;
import Resbar.ControladorAgregarOrden;
import Resbar.clasenuevaorden;
import Resbar.controladorcategoria;
import Resbar.controladorproducto;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author NERIO
 */
public class nueva_orden extends javax.swing.JFrame {

    /**
     * Creates new form nueva_orden
     */
    private String fechaActual="2019-06-18 00:00:00";
    
    ResultSet rs = null;
    controladorproducto productos = new controladorproducto();
    controladorcategoria categorias = new controladorcategoria();
    DefaultTableModel modeloorden = new DefaultTableModel();
    String seleccionado;
    
        clasenuevaorden id = new clasenuevaorden();
    
    
    
    
    public void llenandotextos(int IdOrden) 
    {
        txtorden.setText(String.valueOf(IdOrden));

    }
    
      public void Contar() {
        int mayor = 0;
        rs = null;
        rs = id.contarRegistros();

        try {
            while (rs.next()) {
                mayor = rs.getInt(1);
                if (mayor != 0) {
                    mayor = mayor + 1;
                    if (mayor > 0 && mayor < 10) {
                        txtorden.setText("000" + mayor);
                    } else if (mayor > 9 && mayor < 100) {
                        txtorden.setText("00" + mayor);
                    } else if (mayor > 99 && mayor < 1000) {
                        txtorden.setText("0" + mayor);
                    } else {
                        txtorden.setText(String.valueOf(mayor));
                    }
                } else {
                    txtorden.setText("0001");
                }
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "AVISO DEL SISTEMA", 0);
        }
    }
    
    
    
    
    
    
    
    
  public void llenarbotones(){
      rs=null;
      //Llenando el cmbDepartamento mediante un modelo
        rs = categorias.llenarCategorias();
           Vector producto=new Vector(3,5);
        try {
            while (rs.next()) {
               producto.addElement(rs.getString(2));
               
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Error", 0);
        }
          btnplatos.setText((String) producto.elementAt(0));
        btnbebidas.setText((String) producto.elementAt(1));
        btnpostres.setText((String) producto.elementAt(2));
       
      
  }
    
    
    public nueva_orden() {
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("/imagenes/imagenrestaurante.png")).getImage());
        this.setTitle("Nueva Orden");
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        llenarbotones();
         bebidas.setVisible(false);
         postres.setVisible(false);
         platos.setVisible(true);
        Contar();
        modeloorden.addColumn("IdProductos");
        modeloorden.addColumn("Productos");
        modeloorden.addColumn("Cantidad");
        modeloorden.addColumn("P/u");
        modeloorden.addColumn("Sub-Total");
         
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnpostres = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txttotal = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnguardar = new javax.swing.JButton();
        txtorden = new javax.swing.JTextField();
        txtmesa = new javax.swing.JTextField();
        txtcliente = new javax.swing.JTextField();
        txtobservacion = new javax.swing.JTextField();
        txtmesero = new javax.swing.JTextField();
        btnsalir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnplatos = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnbebidas = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblordenes = new javax.swing.JTable();
        btneliminar = new javax.swing.JButton();
        btnagregar = new javax.swing.JButton();
        postres = new org.edisoncor.gui.panel.PanelRound();
        btnpostre1 = new javax.swing.JButton();
        btnpostre2 = new javax.swing.JButton();
        btnpostre3 = new javax.swing.JButton();
        btnpostre4 = new javax.swing.JButton();
        btnpostre5 = new javax.swing.JButton();
        btnpostre6 = new javax.swing.JButton();
        btnpostre7 = new javax.swing.JButton();
        btnpostre8 = new javax.swing.JButton();
        btnpostre9 = new javax.swing.JButton();
        btnpostre10 = new javax.swing.JButton();
        btnpostre11 = new javax.swing.JButton();
        btnpostre12 = new javax.swing.JButton();
        bebidas = new org.edisoncor.gui.panel.PanelRound();
        btnbebida1 = new javax.swing.JButton();
        btnbebida2 = new javax.swing.JButton();
        btnbebida3 = new javax.swing.JButton();
        btnbebida4 = new javax.swing.JButton();
        btnbebida5 = new javax.swing.JButton();
        btnbebida6 = new javax.swing.JButton();
        btnbebida7 = new javax.swing.JButton();
        btnbebida8 = new javax.swing.JButton();
        btnbebida9 = new javax.swing.JButton();
        btnbebida10 = new javax.swing.JButton();
        btnbebida11 = new javax.swing.JButton();
        btnbebida12 = new javax.swing.JButton();
        platos = new org.edisoncor.gui.panel.PanelRound();
        btnplato1 = new javax.swing.JButton();
        btnplato2 = new javax.swing.JButton();
        btnplato3 = new javax.swing.JButton();
        btnplato4 = new javax.swing.JButton();
        btnplato5 = new javax.swing.JButton();
        btnplato6 = new javax.swing.JButton();
        btnplato7 = new javax.swing.JButton();
        btnplato8 = new javax.swing.JButton();
        btnplato9 = new javax.swing.JButton();
        btnplato10 = new javax.swing.JButton();
        btnplato11 = new javax.swing.JButton();
        btnplato12 = new javax.swing.JButton();
        btnquitar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnpostres.setText("Postres");
        btnpostres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnpostresMouseClicked(evt);
            }
        });
        btnpostres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpostresActionPerformed(evt);
            }
        });
        jPanel1.add(btnpostres, new org.netbeans.lib.awtextra.AbsoluteConstraints(379, 30, 110, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 0, 0));
        jLabel5.setText("Observacion");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 210, 120, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 0, 0));
        jLabel6.setText("Mesero:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 150, -1, -1));

        txttotal.setEditable(false);
        txttotal.setBackground(new java.awt.Color(0, 255, 204));
        txttotal.setFocusable(false);
        jPanel1.add(txttotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 650, 130, -1));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("Total:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 650, -1, -1));

        btnguardar.setBackground(new java.awt.Color(102, 255, 102));
        btnguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/save.png"))); // NOI18N
        btnguardar.setText("guardar");
        btnguardar.setBorder(null);
        btnguardar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnguardarMouseMoved(evt);
            }
        });
        btnguardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnguardarMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnguardarMouseEntered(evt);
            }
        });
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 690, 110, 40));

        txtorden.setEditable(false);
        txtorden.setBackground(new java.awt.Color(0, 255, 204));
        txtorden.setFocusable(false);
        jPanel1.add(txtorden, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 110, 60, -1));

        txtmesa.setBackground(new java.awt.Color(0, 255, 204));
        txtmesa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtmesaKeyTyped(evt);
            }
        });
        jPanel1.add(txtmesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 150, 60, -1));

        txtcliente.setBackground(new java.awt.Color(0, 255, 204));
        txtcliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtclienteKeyTyped(evt);
            }
        });
        jPanel1.add(txtcliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 180, 390, -1));

        txtobservacion.setBackground(new java.awt.Color(0, 255, 204));
        txtobservacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtobservacionActionPerformed(evt);
            }
        });
        txtobservacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtobservacionKeyTyped(evt);
            }
        });
        jPanel1.add(txtobservacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 210, 390, 50));

        txtmesero.setBackground(new java.awt.Color(0, 255, 204));
        txtmesero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmeseroActionPerformed(evt);
            }
        });
        txtmesero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtmeseroKeyTyped(evt);
            }
        });
        jPanel1.add(txtmesero, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 150, 250, -1));

        btnsalir.setBackground(new java.awt.Color(102, 255, 102));
        btnsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/dispose.png"))); // NOI18N
        btnsalir.setBorder(null);
        btnsalir.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnsalirMouseMoved(evt);
            }
        });
        btnsalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnsalirMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnsalirMouseEntered(evt);
            }
        });
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 30, 70, 40));

        jLabel2.setBackground(new java.awt.Color(255, 0, 0));
        jLabel2.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setText("Orden:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 110, 70, 20));

        btnplatos.setText("Platos");
        btnplatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnplatosMouseClicked(evt);
            }
        });
        btnplatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnplatosActionPerformed(evt);
            }
        });
        jPanel1.add(btnplatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 110, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 0));
        jLabel3.setText("Mesa:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 150, 50, 20));

        btnbebidas.setText("Bebidas");
        btnbebidas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnbebidasMouseClicked(evt);
            }
        });
        btnbebidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbebidasActionPerformed(evt);
            }
        });
        jPanel1.add(btnbebidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 0));
        jLabel4.setText("Cliente:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 180, 70, -1));

        tblordenes.setBackground(new java.awt.Color(204, 255, 255));
        tblordenes.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 0), 2, true));
        tblordenes.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        tblordenes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "IdProducto", "Productos", "Cantidad", "P/c", "Subtotal"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Float.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblordenes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane2.setViewportView(tblordenes);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 270, 570, 370));

        btneliminar.setBackground(new java.awt.Color(102, 204, 102));
        btneliminar.setText("-");
        btneliminar.setBorderPainted(false);
        btneliminar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btneliminarMouseMoved(evt);
            }
        });
        btneliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btneliminarMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btneliminarMouseEntered(evt);
            }
        });
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btneliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 650, 50, -1));

        btnagregar.setBackground(new java.awt.Color(102, 204, 102));
        btnagregar.setText("+");
        btnagregar.setBorderPainted(false);
        btnagregar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnagregarMouseMoved(evt);
            }
        });
        btnagregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnagregarMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnagregarMouseEntered(evt);
            }
        });
        btnagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregarActionPerformed(evt);
            }
        });
        jPanel1.add(btnagregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 650, 50, -1));

        postres.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnpostre1.setText("Flan");
        btnpostre1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpostre1ActionPerformed(evt);
            }
        });
        postres.add(btnpostre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 400, 90, 90));

        btnpostre2.setText("Budin");
        btnpostre2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpostre2ActionPerformed(evt);
            }
        });
        postres.add(btnpostre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 100, 90));

        btnpostre3.setText("Bollo");
        btnpostre3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpostre3ActionPerformed(evt);
            }
        });
        postres.add(btnpostre3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, 90, 90));

        btnpostre4.setText("Pastel");
        btnpostre4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpostre4ActionPerformed(evt);
            }
        });
        postres.add(btnpostre4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 100, 90));

        btnpostre5.setText("Milhoja");
        btnpostre5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpostre5ActionPerformed(evt);
            }
        });
        postres.add(btnpostre5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 290, 90, 90));

        btnpostre6.setText("cupcake");
        btnpostre6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpostre6ActionPerformed(evt);
            }
        });
        postres.add(btnpostre6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, -1, 90));

        btnpostre7.setText("Gelato");
        btnpostre7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpostre7ActionPerformed(evt);
            }
        });
        postres.add(btnpostre7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 90, 90));

        btnpostre8.setText("Tiramisu");
        btnpostre8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpostre8ActionPerformed(evt);
            }
        });
        postres.add(btnpostre8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, -1, 90));

        btnpostre9.setText("Alfajor");
        btnpostre9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpostre9ActionPerformed(evt);
            }
        });
        postres.add(btnpostre9, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, 90, 90));

        btnpostre10.setText("Crepa");
        btnpostre10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpostre10ActionPerformed(evt);
            }
        });
        postres.add(btnpostre10, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 400, 90, 90));

        btnpostre11.setText("Gelatina\n");
        btnpostre11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpostre11ActionPerformed(evt);
            }
        });
        postres.add(btnpostre11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 100, 90));

        btnpostre12.setText("Mousse");
        btnpostre12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpostre12ActionPerformed(evt);
            }
        });
        postres.add(btnpostre12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 100, 90));

        jPanel1.add(postres, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 570, 610));

        bebidas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnbebida1.setText("Cafe");
        btnbebida1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbebida1ActionPerformed(evt);
            }
        });
        bebidas.add(btnbebida1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 400, 90, 90));

        btnbebida2.setText("Agua");
        btnbebida2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbebida2ActionPerformed(evt);
            }
        });
        bebidas.add(btnbebida2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 100, 90));

        btnbebida3.setText("Mate");
        btnbebida3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbebida3ActionPerformed(evt);
            }
        });
        bebidas.add(btnbebida3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, 90, 90));

        btnbebida4.setText("Cebada");
        btnbebida4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbebida4ActionPerformed(evt);
            }
        });
        bebidas.add(btnbebida4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 100, 90));

        btnbebida5.setText("Leche");
        btnbebida5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbebida5ActionPerformed(evt);
            }
        });
        bebidas.add(btnbebida5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 290, 90, 90));

        btnbebida6.setText("Licuado");
        btnbebida6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbebida6ActionPerformed(evt);
            }
        });
        bebidas.add(btnbebida6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 100, 90));

        btnbebida7.setText("Te");
        btnbebida7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbebida7ActionPerformed(evt);
            }
        });
        bebidas.add(btnbebida7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 100, 90));

        btnbebida8.setText("Mojito");
        btnbebida8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbebida8ActionPerformed(evt);
            }
        });
        bebidas.add(btnbebida8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 100, 90));

        btnbebida9.setText("Vino");
        btnbebida9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbebida9ActionPerformed(evt);
            }
        });
        bebidas.add(btnbebida9, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, 90, 90));

        btnbebida10.setText("Choco");
        btnbebida10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbebida10ActionPerformed(evt);
            }
        });
        bebidas.add(btnbebida10, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 400, 100, 90));

        btnbebida11.setText("Soda");
        btnbebida11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbebida11ActionPerformed(evt);
            }
        });
        bebidas.add(btnbebida11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 100, 90));

        btnbebida12.setText("Horchata");
        btnbebida12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbebida12ActionPerformed(evt);
            }
        });
        bebidas.add(btnbebida12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, -1, 90));

        jPanel1.add(bebidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 570, 610));

        platos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnplato1.setText("Carne ");
        btnplato1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnplato1ActionPerformed(evt);
            }
        });
        platos.add(btnplato1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 400, 90, 90));

        btnplato2.setText("Estofado");
        btnplato2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnplato2ActionPerformed(evt);
            }
        });
        platos.add(btnplato2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, 90));

        btnplato3.setText("Pasta");
        btnplato3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnplato3ActionPerformed(evt);
            }
        });
        platos.add(btnplato3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, 90, 90));

        btnplato4.setText("Ramen");
        btnplato4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnplato4ActionPerformed(evt);
            }
        });
        platos.add(btnplato4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 100, 90));

        btnplato5.setText("Flauta");
        btnplato5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnplato5ActionPerformed(evt);
            }
        });
        platos.add(btnplato5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 290, 90, 90));

        btnplato6.setText("Sopa");
        btnplato6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnplato6ActionPerformed(evt);
            }
        });
        platos.add(btnplato6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 90, 90));

        btnplato7.setText("Arroz");
        btnplato7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnplato7ActionPerformed(evt);
            }
        });
        platos.add(btnplato7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 90, 90));

        btnplato8.setText("Pescado");
        btnplato8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnplato8ActionPerformed(evt);
            }
        });
        platos.add(btnplato8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, -1, 90));

        btnplato9.setText("Guiso");
        btnplato9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnplato9ActionPerformed(evt);
            }
        });
        platos.add(btnplato9, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, 90, 90));

        btnplato10.setText("Vegetal");
        btnplato10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnplato10ActionPerformed(evt);
            }
        });
        platos.add(btnplato10, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 400, 90, 90));

        btnplato11.setText("Pollo");
        btnplato11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnplato11ActionPerformed(evt);
            }
        });
        platos.add(btnplato11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 100, 90));

        btnplato12.setText("Pupusa");
        btnplato12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnplato12ActionPerformed(evt);
            }
        });
        platos.add(btnplato12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 100, 90));

        jPanel1.add(platos, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 570, 610));

        btnquitar.setBackground(new java.awt.Color(102, 204, 102));
        btnquitar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_Multiply_32px.png"))); // NOI18N
        btnquitar.setBorderPainted(false);
        btnquitar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnquitarMouseMoved(evt);
            }
        });
        btnquitar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnquitarMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnquitarMouseEntered(evt);
            }
        });
        btnquitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnquitarActionPerformed(evt);
            }
        });
        jPanel1.add(btnquitar, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 650, 50, 25));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1383, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 767, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        // TODO add your handling code here:
        dashboard menu=new dashboard();
        menu.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnsalirActionPerformed

    private void txtobservacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtobservacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtobservacionActionPerformed

    private void txtmeseroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmeseroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmeseroActionPerformed

    private void btnguardarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnguardarMouseMoved
        // TODO add your handling code here:
         String texto="Guardar";
btnguardar.setToolTipText(texto);//el metodo setToolTipTex hace que cuando pongo el puntero del raton sobre el boton muestre el nombre del boton
  
    }//GEN-LAST:event_btnguardarMouseMoved

    private void btnsalirMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsalirMouseMoved
        // TODO add your handling code here:
         String texto="Salir";
btnsalir.setToolTipText(texto);//el metodo setToolTipTex hace que cuando pongo el puntero del raton sobre el boton muestre el nombre del boton
  
    }//GEN-LAST:event_btnsalirMouseMoved

    private void btnguardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnguardarMouseEntered
        // TODO add your handling code here:
         btnguardar.setBackground(new Color(0,204,51));//cambia el color del boton cuando paso el puntero sobre el boton
   
    }//GEN-LAST:event_btnguardarMouseEntered

    private void btnguardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnguardarMouseExited
        // TODO add your handling code here:
         btnguardar.setBackground(new Color(102,255,102));//cambia el color del boton cuando paso el puntero sobre el boton
   
    }//GEN-LAST:event_btnguardarMouseExited

    private void btnsalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsalirMouseEntered
        // TODO add your handling code here:
         btnsalir.setBackground(new Color(0,204,51));//cambia el color del boton cuando paso el puntero sobre el boton
   
    }//GEN-LAST:event_btnsalirMouseEntered

    private void btnsalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsalirMouseExited
        // TODO add your handling code here:
         btnsalir.setBackground(new Color(102,255,102));//cambia el color del boton cuando paso el puntero sobre el boton
   
    }//GEN-LAST:event_btnsalirMouseExited

    private void btnagregarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnagregarMouseMoved
        // TODO add your handling code here:
         String texto="Agregar";
btnagregar.setToolTipText(texto);//el metodo setToolTipTex hace que cuando pongo el puntero del raton sobre el boton muestre el nombre del boton
  
    }//GEN-LAST:event_btnagregarMouseMoved

    private void btneliminarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btneliminarMouseMoved
        // TODO add your handling code here:
         String texto="Eliminar";
btneliminar.setToolTipText(texto);//el metodo setToolTipTex hace que cuando pongo el puntero del raton sobre el boton muestre el nombre del boton
  
    }//GEN-LAST:event_btneliminarMouseMoved

    private void btnpostresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpostresActionPerformed
          rs = null;
    seleccionado="3";//es la categoria postres
        rs = productos.productobyid(seleccionado);
      Vector producto=new Vector(12,5);//se crea un vector de 12 de elemntos con un margen de 5 mas si se sobrepasa el limite de 12
      
        try {
            while (rs.next()) {
                producto.addElement(rs.getString(1));//agregando cada elemento de la consulta al vector productos
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Error", 0);
        }
        
        //aqui se agrega cada elemento del vector a los  botones correspondientes
        btnpostre1.setText((String) producto.elementAt(0));
        btnpostre2.setText((String) producto.elementAt(1));
        btnpostre3.setText((String) producto.elementAt(2));
        btnpostre4.setText((String) producto.elementAt(3));
        btnpostre5.setText((String) producto.elementAt(4));
        btnpostre6.setText((String) producto.elementAt(5));
        btnpostre7.setText((String) producto.elementAt(6));
        btnpostre8.setText((String) producto.elementAt(7));
        btnpostre9.setText((String) producto.elementAt(8));
        btnpostre10.setText((String) producto.elementAt(9));
        btnpostre11.setText((String) producto.elementAt(10));
        btnpostre11.setText((String) producto.elementAt(11));
    }//GEN-LAST:event_btnpostresActionPerformed

    private void btnplatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnplatosActionPerformed
          rs = null;
    seleccionado="1";//es la categoria platos
        rs = productos.productobyid(seleccionado);
      Vector producto=new Vector(12,5);//se crea un vector de 12 de elemntos con un margen de 5 mas si se sobrepasa el limite de 12
      
        try {
            while (rs.next()) {
                producto.addElement(rs.getString(1));//agregando cada elemento de la consulta al vector productos
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Error", 0);
        }
        
        //aqui se agrega cada elemento del vector a los  botones correspondientes
        btnplato1.setText((String) producto.elementAt(0));
        btnplato2.setText((String) producto.elementAt(1));
        btnplato3.setText((String) producto.elementAt(2));
        btnplato4.setText((String) producto.elementAt(3));
        btnplato5.setText((String) producto.elementAt(4));
        btnplato6.setText((String) producto.elementAt(5));
        btnplato7.setText((String) producto.elementAt(6));
        btnplato8.setText((String) producto.elementAt(7));
        btnplato9.setText((String) producto.elementAt(8));
        btnplato10.setText((String) producto.elementAt(9));
        btnplato11.setText((String) producto.elementAt(10));
        btnplato11.setText((String) producto.elementAt(11));
                
    }//GEN-LAST:event_btnplatosActionPerformed

    private void btnbebidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbebidasActionPerformed

    rs = null;
    seleccionado="2";//es la categoria bebidas
        rs = productos.productobyid(seleccionado);
      Vector producto=new Vector(12,5);//se crea un vector de 12 de elemntos con un margen de 5 mas si se sobrepasa el limite de 12
      
        try {
            while (rs.next()) {
                producto.addElement(rs.getString(1));//agregando cada elemento de la consulta al vector productos
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Error", 0);
        }
        
        //aqui se agrega cada elemento del vector a los  botones correspondientes
        btnbebida1.setText((String) producto.elementAt(0));
        btnbebida2.setText((String) producto.elementAt(1));
        btnbebida3.setText((String) producto.elementAt(2));
        btnbebida4.setText((String) producto.elementAt(3));
        btnbebida5.setText((String) producto.elementAt(4));
        btnbebida6.setText((String) producto.elementAt(5));
        btnbebida7.setText((String) producto.elementAt(6));
        btnbebida8.setText((String) producto.elementAt(7));
        btnbebida9.setText((String) producto.elementAt(8));
        btnbebida10.setText((String) producto.elementAt(9));
        btnbebida11.setText((String) producto.elementAt(10));
        btnbebida12.setText((String) producto.elementAt(11));
        
        
    }//GEN-LAST:event_btnbebidasActionPerformed

    private void btnplatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnplatosMouseClicked
        this.platos.setVisible(true);
        this.bebidas.setVisible(false);
        this.postres.setVisible(false);
    }//GEN-LAST:event_btnplatosMouseClicked

    private void btnbebidasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbebidasMouseClicked
     this.bebidas.setVisible(true);
        this.platos.setVisible(false);
        this.postres.setVisible(false);



    }//GEN-LAST:event_btnbebidasMouseClicked

    private void btnpostresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnpostresMouseClicked
        // TODO add your handling code here:
        this.bebidas.setVisible(false);
        this.platos.setVisible(false);
        this.postres.setVisible(true);
    }//GEN-LAST:event_btnpostresMouseClicked

    private void btnquitarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnquitarMouseMoved
        // TODO add your handling code here:
       String texto="Quitar";
       btnquitar.setToolTipText(texto);//el metodo setToolTipTex hace que cuando pongo el puntero del raton sobre el boton muestre el nombre del boton
  
    }//GEN-LAST:event_btnquitarMouseMoved

    private void btneliminarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btneliminarMouseEntered
        btneliminar.setBackground(new Color(0,255,102));//cambia el color del boton cuando paso el puntero sobre el boton
        // TODO add your handling code here:
    }//GEN-LAST:event_btneliminarMouseEntered

    private void btneliminarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btneliminarMouseExited
        // TODO add your handling code here:
        btneliminar.setBackground(new Color(102,204,102));//cambia el color del boton cuando paso el puntero sobre el boton
    }//GEN-LAST:event_btneliminarMouseExited

    private void btnagregarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnagregarMouseEntered
        // TODO add your handling code here:
        btnagregar.setBackground(new Color(0,255,102));//cambia el color del boton cuando paso el puntero sobre el boton
    }//GEN-LAST:event_btnagregarMouseEntered

    private void btnagregarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnagregarMouseExited
        // TODO add your handling code here:
        btnagregar.setBackground(new Color(102,204,102));//cambia el color del boton cuando paso el puntero sobre el boton
    }//GEN-LAST:event_btnagregarMouseExited

    private void btnquitarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnquitarMouseEntered
        // TODO add your handling code here:
        btnquitar.setBackground(new Color(0,255,102));//cambia el color del boton cuando paso el puntero sobre el boton
    }//GEN-LAST:event_btnquitarMouseEntered

    private void btnquitarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnquitarMouseExited
        // TODO add your handling code here:
        btnquitar.setBackground(new Color(102,204,102));//cambia el color del boton cuando paso el puntero sobre el boton
    }//GEN-LAST:event_btnquitarMouseExited

    private void txtmesaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmesaKeyTyped
        // TODO add your handling code here:
          char caracter = evt.getKeyChar();
        if (((caracter < '0') || (caracter > '9')) && (caracter != '.') && (caracter != '/') && (caracter != '-')) {
            evt.consume();
        } else if (((caracter > '0') || (caracter < '9'))) {
            evt.consume();
            txtmesa.setText(txtmesa.getText() + String.valueOf(caracter));
        }
    }//GEN-LAST:event_txtmesaKeyTyped

    private void txtmeseroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmeseroKeyTyped
        // TODO add your handling code here:
        char caracter = evt.getKeyChar();
        if (Character.isLetter(caracter) || Character.isSpaceChar(caracter)) {
            evt.consume();
            txtmesero.setText(txtmesero.getText() + String.valueOf(caracter));
        } else if (!Character.isLetter(caracter) || !Character.isSpaceChar(caracter)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtmeseroKeyTyped

    private void txtclienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtclienteKeyTyped
        // TODO add your handling code here:
        char caracter = evt.getKeyChar();
        if (Character.isLetter(caracter) || Character.isSpaceChar(caracter)) {
            evt.consume();
            txtcliente.setText(txtcliente.getText() + String.valueOf(caracter));
        } else if (!Character.isLetter(caracter) || !Character.isSpaceChar(caracter)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtclienteKeyTyped

    private void txtobservacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtobservacionKeyTyped
        // TODO add your handling code here:
        char caracter = evt.getKeyChar();
        if (Character.isLetter(caracter) || Character.isSpaceChar(caracter)) {
            evt.consume();
            txtobservacion.setText(txtobservacion.getText() + String.valueOf(caracter));
        } else if (!Character.isLetter(caracter) || !Character.isSpaceChar(caracter)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtobservacionKeyTyped

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
       
         String IdOrden = txtorden.getText();
        String mesa = txtmesa.getText();
        String mesero = txtmesero.getText();
        String cliente = txtcliente.getText();
        String observacion = txtobservacion.getText();

        if (IdOrden.isEmpty() || mesa.isEmpty() || mesero.isEmpty() || cliente.isEmpty() || observacion.isEmpty()  ) {
            JOptionPane.showMessageDialog(null, "Ingrese todos los campos");
        } else {
            id.insertar(IdOrden, mesa, mesero, cliente, observacion);
            
            txtorden.setText("");
            txtmesa.setText("");
           
            
            JOptionPane.showMessageDialog(null, "Registro agregado");
        }

    }//GEN-LAST:event_btnguardarActionPerformed

    private void btnpostre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpostre1ActionPerformed
       

         int contador=1;
        rs = null;
        Object[] dato=new Object[5]; 
        
          
           rs=productos.traerprecio(btnpostre1.getText());
        dato[1]=btnpostre1.getText();
        dato[2]=""+contador;
        try {
            while (rs.next()) {
                dato[3]=rs.getString(2);
                dato[4]=rs.getString(2);
                dato[0]=rs.getString(1);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Error", 0);
        }
        
     
         modeloorden.addRow(dato);
        tblordenes.setModel(modeloorden);
        this.btnpostre1.setEnabled(false); 


    }//GEN-LAST:event_btnpostre1ActionPerformed

    private void btnpostre2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpostre2ActionPerformed
        // TODO add your handling code here:
       int contador=1;
        rs = null;
        Object[] dato=new Object[5]; 
        
          
           rs=productos.traerprecio(btnpostre2.getText());
        dato[1]=btnpostre2.getText();
        dato[2]=""+contador;
        try {
            while (rs.next()) {
                dato[3]=rs.getString(2);
                dato[4]=rs.getString(2);
                dato[0]=rs.getString(1);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Error", 0);
        }
        
     
         modeloorden.addRow(dato);
        tblordenes.setModel(modeloorden);
        this.btnpostre2.setEnabled(false); 


    }//GEN-LAST:event_btnpostre2ActionPerformed

    private void btnpostre3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpostre3ActionPerformed
        // TODO add your handling code here:
       int contador=1;
        rs = null;
        Object[] dato=new Object[5]; 
        
          
           rs=productos.traerprecio(btnpostre3.getText());
        dato[1]=btnpostre3.getText();
        dato[2]=""+contador;
        try {
            while (rs.next()) {
                dato[3]=rs.getString(2);
                dato[4]=rs.getString(2);
                dato[0]=rs.getString(1);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Error", 0);
        }
        
     
         modeloorden.addRow(dato);
        tblordenes.setModel(modeloorden);
        this.btnpostre3.setEnabled(false); 


    }//GEN-LAST:event_btnpostre3ActionPerformed

    private void btnpostre4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpostre4ActionPerformed
        // TODO add your handling code here:
       int contador=1;
        rs = null;
        Object[] dato=new Object[5]; 
        
          
           rs=productos.traerprecio(btnpostre4.getText());
        dato[1]=btnpostre4.getText();
        dato[2]=""+contador;
        try {
            while (rs.next()) {
                dato[3]=rs.getString(2);
                dato[4]=rs.getString(2);
                dato[0]=rs.getString(1);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Error", 0);
        }
        
     
         modeloorden.addRow(dato);
        tblordenes.setModel(modeloorden);
        this.btnpostre4.setEnabled(false); 


    }//GEN-LAST:event_btnpostre4ActionPerformed

    private void btnpostre5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpostre5ActionPerformed
        // TODO add your handling code here:
       int contador=1;
        rs = null;
        Object[] dato=new Object[5]; 
        
          
           rs=productos.traerprecio(btnpostre5.getText());
        dato[1]=btnpostre5.getText();
        dato[2]=""+contador;
        try {
            while (rs.next()) {
                dato[3]=rs.getString(2);
                dato[4]=rs.getString(2);
                dato[0]=rs.getString(1);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Error", 0);
        }
        
     
         modeloorden.addRow(dato);
        tblordenes.setModel(modeloorden);
        this.btnpostre5.setEnabled(false); 


    }//GEN-LAST:event_btnpostre5ActionPerformed

    private void btnpostre6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpostre6ActionPerformed
        // TODO add your handling code here:
       int contador=1;
        rs = null;
        Object[] dato=new Object[5]; 
        
          
           rs=productos.traerprecio(btnpostre6.getText());
        dato[1]=btnpostre6.getText();
        dato[2]=""+contador;
        try {
            while (rs.next()) {
                dato[3]=rs.getString(2);
                dato[4]=rs.getString(2);
                dato[0]=rs.getString(1);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Error", 0);
        }
        
     
         modeloorden.addRow(dato);
        tblordenes.setModel(modeloorden);
        this.btnpostre6.setEnabled(false); 


    }//GEN-LAST:event_btnpostre6ActionPerformed

    private void btnpostre7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpostre7ActionPerformed
        // TODO add your handling code here:
       int contador=1;
        rs = null;
        Object[] dato=new Object[5]; 
        
          
           rs=productos.traerprecio(btnpostre7.getText());
        dato[1]=btnpostre7.getText();
        dato[2]=""+contador;
        try {
            while (rs.next()) {
                dato[3]=rs.getString(2);
                dato[4]=rs.getString(2);
                dato[0]=rs.getString(1);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Error", 0);
        }
        
     
         modeloorden.addRow(dato);
        tblordenes.setModel(modeloorden);
        this.btnpostre7.setEnabled(false); 


    }//GEN-LAST:event_btnpostre7ActionPerformed

    private void btnpostre8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpostre8ActionPerformed
        // TODO add your handling code here:
       int contador=1;
        rs = null;
        Object[] dato=new Object[5]; 
        
          
           rs=productos.traerprecio(btnpostre8.getText());
        dato[1]=btnpostre8.getText();
        dato[2]=""+contador;
        try {
            while (rs.next()) {
                dato[3]=rs.getString(2);
                dato[4]=rs.getString(2);
                dato[0]=rs.getString(1);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Error", 0);
        }
        
     
         modeloorden.addRow(dato);
        tblordenes.setModel(modeloorden);
        this.btnpostre8.setEnabled(false); 


    }//GEN-LAST:event_btnpostre8ActionPerformed

    private void btnpostre9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpostre9ActionPerformed
        // TODO add your handling code here:
       int contador=1;
        rs = null;
        Object[] dato=new Object[5]; 
        
          
           rs=productos.traerprecio(btnpostre9.getText());
        dato[1]=btnpostre9.getText();
        dato[2]=""+contador;
        try {
            while (rs.next()) {
                dato[3]=rs.getString(2);
                dato[4]=rs.getString(2);
                dato[0]=rs.getString(1);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Error", 0);
        }
        
     
         modeloorden.addRow(dato);
        tblordenes.setModel(modeloorden);
        this.btnpostre9.setEnabled(false); 


    }//GEN-LAST:event_btnpostre9ActionPerformed

    private void btnpostre10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpostre10ActionPerformed
        // TODO add your handling code here:
       int contador=1;
        rs = null;
        Object[] dato=new Object[5]; 
        
          
           rs=productos.traerprecio(btnpostre10.getText());
        dato[1]=btnpostre10.getText();
        dato[2]=""+contador;
        try {
            while (rs.next()) {
                dato[3]=rs.getString(2);
                dato[4]=rs.getString(2);
                dato[0]=rs.getString(1);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Error", 0);
        }
        
     
         modeloorden.addRow(dato);
        tblordenes.setModel(modeloorden);
        this.btnpostre10.setEnabled(false); 


    }//GEN-LAST:event_btnpostre10ActionPerformed

    private void btnpostre11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpostre11ActionPerformed
        // TODO add your handling code here:
       int contador=1;
        rs = null;
        Object[] dato=new Object[5]; 
        
          
           rs=productos.traerprecio(btnpostre11.getText());
        dato[1]=btnpostre11.getText();
        dato[2]=""+contador;
        try {
            while (rs.next()) {
                dato[3]=rs.getString(2);
                dato[4]=rs.getString(2);
                dato[0]=rs.getString(1);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Error", 0);
        }
        
     
         modeloorden.addRow(dato);
        tblordenes.setModel(modeloorden);
        this.btnpostre11.setEnabled(false); 


    }//GEN-LAST:event_btnpostre11ActionPerformed

    private void btnpostre12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpostre12ActionPerformed
        // TODO add your handling code here:
       int contador=1;
        rs = null;
        Object[] dato=new Object[5]; 
        
          
           rs=productos.traerprecio(btnpostre12.getText());
        dato[1]=btnpostre12.getText();
        dato[2]=""+contador;
        try {
            while (rs.next()) {
                dato[3]=rs.getString(2);
                dato[4]=rs.getString(2);
                dato[0]=rs.getString(1);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Error", 0);
        }
        
     
         modeloorden.addRow(dato);
        tblordenes.setModel(modeloorden);
        this.btnpostre12.setEnabled(false); 


    }//GEN-LAST:event_btnpostre12ActionPerformed

    private void btnbebida1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbebida1ActionPerformed
        // TODO add your handling code here:
        int contador=1;
        rs = null;
        Object[] dato=new Object[5]; 
        
          
           rs=productos.traerprecio(btnbebida1.getText());
        dato[1]=btnbebida1.getText();
        dato[2]=""+contador;
        try {
            while (rs.next()) {
                dato[3]=rs.getString(2);
                dato[4]=rs.getString(2);
                dato[0]=rs.getString(1);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Error", 0);
        }
        
     
         modeloorden.addRow(dato);
        tblordenes.setModel(modeloorden);
        this.btnbebida1.setEnabled(false); 


    }//GEN-LAST:event_btnbebida1ActionPerformed

    private void btnbebida2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbebida2ActionPerformed
        // TODO add your handling code here:
          int contador=1;
        rs = null;
        Object[] dato=new Object[5]; 
        
          
           rs=productos.traerprecio(btnbebida2.getText());
        dato[1]=btnbebida2.getText();
        dato[2]=""+contador;
        try {
            while (rs.next()) {
                dato[3]=rs.getString(2);
                dato[4]=rs.getString(2);
                dato[0]=rs.getString(1);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Error", 0);
        }
        
     
         modeloorden.addRow(dato);
        tblordenes.setModel(modeloorden);
        this.btnbebida2.setEnabled(false); 
    }//GEN-LAST:event_btnbebida2ActionPerformed

    private void btnbebida3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbebida3ActionPerformed
        // TODO add your handling code here:
         int contador=1;
        rs = null;
        Object[] dato=new Object[5]; 
        
          
           rs=productos.traerprecio(btnbebida3.getText());
        dato[1]=btnbebida3.getText();
        dato[2]=""+contador;
        try {
            while (rs.next()) {
                dato[3]=rs.getString(2);
                dato[4]=rs.getString(2);
                dato[0]=rs.getString(1);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Error", 0);
        }
        
     
         modeloorden.addRow(dato);
        tblordenes.setModel(modeloorden);
        this.btnbebida3.setEnabled(false); 
    }//GEN-LAST:event_btnbebida3ActionPerformed

    private void btnbebida4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbebida4ActionPerformed
        // TODO add your handling code here:
          int contador=1;
        rs = null;
        Object[] dato=new Object[5]; 
        
          
           rs=productos.traerprecio(btnbebida4.getText());
        dato[1]=btnbebida4.getText();
        dato[2]=""+contador;
        try {
            while (rs.next()) {
                dato[3]=rs.getString(2);
                dato[4]=rs.getString(2);
                dato[0]=rs.getString(1);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Error", 0);
        }
        
     
         modeloorden.addRow(dato);
        tblordenes.setModel(modeloorden);
        this.btnbebida4.setEnabled(false); 
    }//GEN-LAST:event_btnbebida4ActionPerformed

    private void btnbebida5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbebida5ActionPerformed
        // TODO add your handling code here:
          int contador=1;
        rs = null;
        Object[] dato=new Object[5]; 
        
          
           rs=productos.traerprecio(btnbebida5.getText());
        dato[1]=btnbebida5.getText();
        dato[2]=""+contador;
        try {
            while (rs.next()) {
                dato[3]=rs.getString(2);
                dato[4]=rs.getString(2);
                dato[0]=rs.getString(1);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Error", 0);
        }
        
     
         modeloorden.addRow(dato);
        tblordenes.setModel(modeloorden);
        this.btnbebida5.setEnabled(false); 
    }//GEN-LAST:event_btnbebida5ActionPerformed

    private void btnbebida6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbebida6ActionPerformed
        // TODO add your handling code here:
          int contador=1;
        rs = null;
        Object[] dato=new Object[5]; 
        
          
           rs=productos.traerprecio(btnbebida6.getText());
        dato[1]=btnbebida6.getText();
        dato[2]=""+contador;
        try {
            while (rs.next()) {
                dato[3]=rs.getString(2);
                dato[4]=rs.getString(2);
                dato[0]=rs.getString(1);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Error", 0);
        }
        
     
         modeloorden.addRow(dato);
        tblordenes.setModel(modeloorden);
        this.btnbebida6.setEnabled(false); 
    }//GEN-LAST:event_btnbebida6ActionPerformed

    private void btnbebida7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbebida7ActionPerformed
        // TODO add your handling code here:
          int contador=1;
        rs = null;
        Object[] dato=new Object[5]; 
        
          
           rs=productos.traerprecio(btnbebida7.getText());
        dato[1]=btnbebida7.getText();
        dato[2]=""+contador;
        try {
            while (rs.next()) {
                dato[3]=rs.getString(2);
                dato[4]=rs.getString(2);
                dato[0]=rs.getString(1);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Error", 0);
        }
        
     
         modeloorden.addRow(dato);
        tblordenes.setModel(modeloorden);
        this.btnbebida7.setEnabled(false); 
    }//GEN-LAST:event_btnbebida7ActionPerformed

    private void btnbebida8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbebida8ActionPerformed
        // TODO add your handling code here:
         int contador=1;
        rs = null;
        Object[] dato=new Object[5]; 
        
          
           rs=productos.traerprecio(btnbebida8.getText());
        dato[1]=btnbebida8.getText();
        dato[2]=""+contador;
        try {
            while (rs.next()) {
                dato[3]=rs.getString(2);
                dato[4]=rs.getString(2);
                dato[0]=rs.getString(1);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Error", 0);
        }
        
     
         modeloorden.addRow(dato);
        tblordenes.setModel(modeloorden);
        this.btnbebida8.setEnabled(false); 
    }//GEN-LAST:event_btnbebida8ActionPerformed

    private void btnbebida9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbebida9ActionPerformed
        // TODO add your handling code here:
          int contador=1;
        rs = null;
        Object[] dato=new Object[5]; 
        
          
           rs=productos.traerprecio(btnbebida9.getText());
        dato[1]=btnbebida9.getText();
        dato[2]=""+contador;
        try {
            while (rs.next()) {
                dato[3]=rs.getString(2);
                dato[4]=rs.getString(2);
                dato[0]=rs.getString(1);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Error", 0);
        }
        
     
         modeloorden.addRow(dato);
        tblordenes.setModel(modeloorden);
        this.btnbebida9.setEnabled(false); 
    }//GEN-LAST:event_btnbebida9ActionPerformed

    private void btnbebida10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbebida10ActionPerformed
        // TODO add your handling code here:
          int contador=1;
        rs = null;
        Object[] dato=new Object[5]; 
        
          
           rs=productos.traerprecio(btnbebida10.getText());
        dato[1]=btnbebida10.getText();
        dato[2]=""+contador;
        try {
            while (rs.next()) {
                dato[3]=rs.getString(2);
                dato[4]=rs.getString(2);
                dato[0]=rs.getString(1);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Error", 0);
        }
        
     
         modeloorden.addRow(dato);
        tblordenes.setModel(modeloorden);
        this.btnbebida10.setEnabled(false); 
    }//GEN-LAST:event_btnbebida10ActionPerformed

    private void btnbebida11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbebida11ActionPerformed
        // TODO add your handling code here:
          int contador=1;
        rs = null;
        Object[] dato=new Object[5]; 
        
          
           rs=productos.traerprecio(btnbebida11.getText());
        dato[1]=btnbebida11.getText();
        dato[2]=""+contador;
        try {
            while (rs.next()) {
                dato[3]=rs.getString(2);
                dato[4]=rs.getString(2);
                dato[0]=rs.getString(1);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Error", 0);
        }
        
     
         modeloorden.addRow(dato);
        tblordenes.setModel(modeloorden);
        this.btnbebida11.setEnabled(false); 
    }//GEN-LAST:event_btnbebida11ActionPerformed

    private void btnbebida12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbebida12ActionPerformed
        // TODO add your handling code here:
        int contador=1;
        rs = null;
        Object[] dato=new Object[5]; 
        
          
           rs=productos.traerprecio(btnbebida12.getText());
        dato[1]=btnbebida12.getText();
        dato[2]=""+contador;
        try {
            while (rs.next()) {
                dato[3]=rs.getString(2);
                dato[4]=rs.getString(2);
                dato[0]=rs.getString(1);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Error", 0);
        }
        
     
         modeloorden.addRow(dato);
        tblordenes.setModel(modeloorden);
        this.btnbebida12.setEnabled(false); 
    }//GEN-LAST:event_btnbebida12ActionPerformed

    private void btnplato1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnplato1ActionPerformed
        // TODO add your handling code here:
        int contador=1;
        rs = null;
        Object[] dato=new Object[5]; 
        
          
           rs=productos.traerprecio(btnplato1.getText());
        dato[1]=btnplato1.getText();
        dato[2]=""+contador;
        try {
            while (rs.next()) {
                dato[3]=rs.getString(2);
                dato[4]=rs.getString(2);
                dato[0]=rs.getString(1);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Error", 0);
        }
        
     
         modeloorden.addRow(dato);
        tblordenes.setModel(modeloorden);
        this.btnplato1.setEnabled(false); 
    }//GEN-LAST:event_btnplato1ActionPerformed

    private void btnplato2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnplato2ActionPerformed
        // TODO add your handling code here:
         int contador=1;
        rs = null;
        Object[] dato=new Object[5]; 
        
          
           rs=productos.traerprecio(btnplato2.getText());
        dato[1]=btnplato2.getText();
        dato[2]=""+contador;
        try {
            while (rs.next()) {
                dato[3]=rs.getString(2);
                dato[4]=rs.getString(2);
                dato[0]=rs.getString(1);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Error", 0);
        }
        
     
         modeloorden.addRow(dato);
        tblordenes.setModel(modeloorden);
        this.btnplato2.setEnabled(false); 
    }//GEN-LAST:event_btnplato2ActionPerformed

    private void btnplato3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnplato3ActionPerformed
        // TODO add your handling code here:
         int contador=1;
        rs = null;
        Object[] dato=new Object[5]; 
        
          
           rs=productos.traerprecio(btnplato3.getText());
        dato[1]=btnplato3.getText();
        dato[2]=""+contador;
        try {
            while (rs.next()) {
                dato[3]=rs.getString(2);
                dato[4]=rs.getString(2);
                dato[0]=rs.getString(1);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Error", 0);
        }
        
     
         modeloorden.addRow(dato);
        tblordenes.setModel(modeloorden);
        this.btnplato3.setEnabled(false); 
    }//GEN-LAST:event_btnplato3ActionPerformed

    private void btnplato4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnplato4ActionPerformed
        // TODO add your handling code here:
         int contador=1;
        rs = null;
        Object[] dato=new Object[5]; 
        
          
           rs=productos.traerprecio(btnplato4.getText());
        dato[1]=btnplato4.getText();
        dato[2]=""+contador;
        try {
            while (rs.next()) {
                dato[3]=rs.getString(2);
                dato[4]=rs.getString(2);
                dato[0]=rs.getString(1);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Error", 0);
        }
        
     
         modeloorden.addRow(dato);
        tblordenes.setModel(modeloorden);
        this.btnplato4.setEnabled(false); 
    }//GEN-LAST:event_btnplato4ActionPerformed

    private void btnplato5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnplato5ActionPerformed
        // TODO add your handling code here:
          int contador=1;
        rs = null;
        Object[] dato=new Object[5]; 
        
          
           rs=productos.traerprecio(btnplato5.getText());
        dato[1]=btnplato5.getText();
        dato[2]=""+contador;
        try {
            while (rs.next()) {
                dato[3]=rs.getString(2);
                dato[4]=rs.getString(2);
                dato[0]=rs.getString(1);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Error", 0);
        }
        
     
         modeloorden.addRow(dato);
        tblordenes.setModel(modeloorden);
        this.btnplato5.setEnabled(false); 
    }//GEN-LAST:event_btnplato5ActionPerformed

    private void btnplato6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnplato6ActionPerformed
        // TODO add your handling code here:
          int contador=1;
        rs = null;
        Object[] dato=new Object[5]; 
        
          
           rs=productos.traerprecio(btnplato6.getText());
        dato[1]=btnplato6.getText();
        dato[2]=""+contador;
        try {
            while (rs.next()) {
                dato[3]=rs.getString(2);
                dato[4]=rs.getString(2);
                dato[0]=rs.getString(1);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Error", 0);
        }
        
     
         modeloorden.addRow(dato);
        tblordenes.setModel(modeloorden);
        this.btnplato6.setEnabled(false); 
    }//GEN-LAST:event_btnplato6ActionPerformed

    private void btnplato7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnplato7ActionPerformed
        // TODO add your handling code here:
          int contador=1;
        rs = null;
        Object[] dato=new Object[5]; 
        
          
           rs=productos.traerprecio(btnplato7.getText());
        dato[1]=btnplato7.getText();
        dato[2]=""+contador;
        try {
            while (rs.next()) {
                dato[3]=rs.getString(2);
                dato[4]=rs.getString(2);
                dato[0]=rs.getString(1);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Error", 0);
        }
        
     
         modeloorden.addRow(dato);
        tblordenes.setModel(modeloorden);
        this.btnplato7.setEnabled(false); 
    }//GEN-LAST:event_btnplato7ActionPerformed

    private void btnplato8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnplato8ActionPerformed
        // TODO add your handling code here:
         int contador=1;
        rs = null;
        Object[] dato=new Object[5]; 
        
          
           rs=productos.traerprecio(btnplato8.getText());
        dato[1]=btnplato8.getText();
        dato[2]=""+contador;
        try {
            while (rs.next()) {
                dato[3]=rs.getString(2);
                dato[4]=rs.getString(2);
                dato[0]=rs.getString(1);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Error", 0);
        }
        
     
         modeloorden.addRow(dato);
        tblordenes.setModel(modeloorden);
        this.btnplato8.setEnabled(false); 
    }//GEN-LAST:event_btnplato8ActionPerformed

    private void btnplato9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnplato9ActionPerformed
        // TODO add your handling code here:
         int contador=1;
        rs = null;
        Object[] dato=new Object[5]; 
        
          
           rs=productos.traerprecio(btnplato9.getText());
        dato[1]=btnplato9.getText();
        dato[2]=""+contador;
        try {
            while (rs.next()) {
                dato[3]=rs.getString(2);
                dato[4]=rs.getString(2);
                dato[0]=rs.getString(1);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Error", 0);
        }
        
     
         modeloorden.addRow(dato);
        tblordenes.setModel(modeloorden);
        this.btnplato9.setEnabled(false); 
    }//GEN-LAST:event_btnplato9ActionPerformed

    private void btnplato10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnplato10ActionPerformed
        // TODO add your handling code here:
          int contador=1;
        rs = null;
        Object[] dato=new Object[5]; 
        
          
           rs=productos.traerprecio(btnplato10.getText());
        dato[1]=btnplato10.getText();
        dato[2]=""+contador;
        try {
            while (rs.next()) {
                dato[3]=rs.getString(2);
                dato[4]=rs.getString(2);
                dato[0]=rs.getString(1);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Error", 0);
        }
        
     
         modeloorden.addRow(dato);
        tblordenes.setModel(modeloorden);
        this.btnplato10.setEnabled(false); 
    }//GEN-LAST:event_btnplato10ActionPerformed

    private void btnplato11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnplato11ActionPerformed
        // TODO add your handling code here:
          int contador=1;
        rs = null;
        Object[] dato=new Object[5]; 
        
          
           rs=productos.traerprecio(btnplato11.getText());
        dato[1]=btnplato11.getText();
        dato[2]=""+contador;
        try {
            while (rs.next()) {
                dato[3]=rs.getString(2);
                dato[4]=rs.getString(2);
                dato[0]=rs.getString(1);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Error", 0);
        }
        
     
         modeloorden.addRow(dato);
        tblordenes.setModel(modeloorden);
        this.btnplato11.setEnabled(false); 
    }//GEN-LAST:event_btnplato11ActionPerformed

    private void btnplato12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnplato12ActionPerformed
        // TODO add your handling code here:
         int contador=1;
        rs = null;
        Object[] dato=new Object[5]; 
        
          
           rs=productos.traerprecio(btnplato12.getText());
        dato[1]=btnplato12.getText();
        dato[2]=""+contador;
        try {
            while (rs.next()) {
                dato[3]=rs.getString(2);
                dato[4]=rs.getString(2);
                dato[0]=rs.getString(1);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Error", 0);
        }
        
     
         modeloorden.addRow(dato);
        tblordenes.setModel(modeloorden);
        this.btnplato12.setEnabled(false); 
    }//GEN-LAST:event_btnplato12ActionPerformed

    
    int estatico;
    String valor,valorp;
    int Nvalor=0;
    double subtotal=0;
    
    private void btnagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregarActionPerformed
        // TODO add your handling code here:
        estatico=1;
        if (tblordenes.getSelectedRow() != -1) //saber si esta seleccionada la fila en la tabla
            
        {
//            int cantidad=Integer.parseInt(modeloorden.getValueAt(tblordenes.getSelectedRow(), 1).toString());//mando la informacion de la fila a los txt donde se editara la informacion en este caso para el id
//          cantidad=cantidad+1;
           //dato[1]=""+cantidad;
            
          valor=String.valueOf(tblordenes.getValueAt(tblordenes.getSelectedRow(), 2));
          Nvalor=Integer.parseInt(valor)+estatico;
           tblordenes.setValueAt(Nvalor,tblordenes.getSelectedRow(), 2);
            valorp=String.valueOf(tblordenes.getValueAt(tblordenes.getSelectedRow(), 3));
            subtotal=Double.parseDouble(valorp)*Nvalor;
            tblordenes.setValueAt(subtotal,tblordenes.getSelectedRow(), 4);
           
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione un elemento para agregar o eliminar productos", null, JOptionPane.WARNING_MESSAGE);
         } 

    }//GEN-LAST:event_btnagregarActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        // TODO add your handling code here:
         estatico=1;
        if (tblordenes.getSelectedRow() != -1) //saber si esta seleccionada la fila en la tabla
            
        {
            valor=String.valueOf(tblordenes.getValueAt(tblordenes.getSelectedRow(), 2));
          Nvalor=Integer.parseInt(valor);
            if(Nvalor>1){

          valor=String.valueOf(tblordenes.getValueAt(tblordenes.getSelectedRow(), 2));
          Nvalor=Integer.parseInt(valor)-estatico;
           tblordenes.setValueAt(Nvalor,tblordenes.getSelectedRow(), 2);
           valorp=String.valueOf(tblordenes.getValueAt(tblordenes.getSelectedRow(), 3));
            subtotal=Double.parseDouble(valorp)*Nvalor;
            tblordenes.setValueAt(subtotal,tblordenes.getSelectedRow(), 4);
            }else{
                JOptionPane.showMessageDialog(null, "No se puede eliminar cantidades iguales a uno");
        } 
            
        }
        else {
            JOptionPane.showMessageDialog(null, "Seleccione un elemento para agregar o eliminar productos", null, JOptionPane.WARNING_MESSAGE);
         }
    }//GEN-LAST:event_btneliminarActionPerformed

    private void btnquitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnquitarActionPerformed
        // TODO add your handling code here:
        
        if (tblordenes.getSelectedRow() != -1) //saber si esta seleccionada la fila en la tabla
            
        {
            
          modeloorden.removeRow(tblordenes.getSelectedRow()); 
           
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione un elemento para eliminar", null, JOptionPane.WARNING_MESSAGE);
         } 
    }//GEN-LAST:event_btnquitarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(agregar_producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(agregar_producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(agregar_producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(agregar_producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new agregar_producto("0").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.panel.PanelRound bebidas;
    private javax.swing.JButton btnagregar;
    private javax.swing.JButton btnbebida1;
    private javax.swing.JButton btnbebida10;
    private javax.swing.JButton btnbebida11;
    private javax.swing.JButton btnbebida12;
    private javax.swing.JButton btnbebida2;
    private javax.swing.JButton btnbebida3;
    private javax.swing.JButton btnbebida4;
    private javax.swing.JButton btnbebida5;
    private javax.swing.JButton btnbebida6;
    private javax.swing.JButton btnbebida7;
    private javax.swing.JButton btnbebida8;
    private javax.swing.JButton btnbebida9;
    private javax.swing.JButton btnbebidas;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnplato1;
    private javax.swing.JButton btnplato10;
    private javax.swing.JButton btnplato11;
    private javax.swing.JButton btnplato12;
    private javax.swing.JButton btnplato2;
    private javax.swing.JButton btnplato3;
    private javax.swing.JButton btnplato4;
    private javax.swing.JButton btnplato5;
    private javax.swing.JButton btnplato6;
    private javax.swing.JButton btnplato7;
    private javax.swing.JButton btnplato8;
    private javax.swing.JButton btnplato9;
    private javax.swing.JButton btnplatos;
    private javax.swing.JButton btnpostre1;
    private javax.swing.JButton btnpostre10;
    private javax.swing.JButton btnpostre11;
    private javax.swing.JButton btnpostre12;
    private javax.swing.JButton btnpostre2;
    private javax.swing.JButton btnpostre3;
    private javax.swing.JButton btnpostre4;
    private javax.swing.JButton btnpostre5;
    private javax.swing.JButton btnpostre6;
    private javax.swing.JButton btnpostre7;
    private javax.swing.JButton btnpostre8;
    private javax.swing.JButton btnpostre9;
    private javax.swing.JButton btnpostres;
    private javax.swing.JButton btnquitar;
    private javax.swing.JButton btnsalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private org.edisoncor.gui.panel.PanelRound platos;
    private org.edisoncor.gui.panel.PanelRound postres;
    private javax.swing.JTable tblordenes;
    private javax.swing.JTextField txtcliente;
    private javax.swing.JTextField txtmesa;
    private javax.swing.JTextField txtmesero;
    private javax.swing.JTextField txtobservacion;
    private javax.swing.JTextField txtorden;
    private javax.swing.JTextField txttotal;
    // End of variables declaration//GEN-END:variables
}
