
import Resbar.controladorproducto;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author willi
 */
public class productos extends javax.swing.JFrame {

    /**
     * Creates new form productos
     */
    
    DefaultTableModel modeloProducto = new DefaultTableModel();
    ResultSet rs = null;
    controladorproducto productos = new controladorproducto();
    String seleccionado;
    
    
    public productos() {
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("/imagenes/imagenrestaurante.png")).getImage());
        this.setTitle("Productos");
         this.setLocationRelativeTo(null);
         
         panelmodificar.setVisible(false);
        modeloProducto.addColumn("IdCategorias");
        modeloProducto.addColumn("Nombre");
        modeloProducto.addColumn("Precio");
           
    }
    
    
    private void Producto(String seleccionado) {
        rs = null;
        rs = productos.llenarProductos(seleccionado);
        //modeloProducto.addColumn("IdCategorias");
        //modeloProducto.addColumn("nombre");
        String[] dato=new String[3]; 
        
        try {
            while (rs.next()) {
                dato[0]=rs.getString(1);
                dato[1]=rs.getString(2);
                dato[2]=rs.getString(3);
                modeloProducto.addRow(dato);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Error", 0);
        }
        tblproducto.setModel(modeloProducto);
    }
    
   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelproducto = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmbcategorias = new javax.swing.JComboBox<String>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblproducto = new javax.swing.JTable();
        btnnuevo = new javax.swing.JButton();
        btnmodificar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        btnsalir = new javax.swing.JButton();
        panelmodificar = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        btnguardar = new javax.swing.JButton();
        btndescartar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtprecio = new javax.swing.JTextField();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Productos");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        panelproducto.setBackground(new java.awt.Color(0, 0, 0));
        panelproducto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 102));
        jLabel1.setText("productos");
        panelproducto.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 40, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 102));
        jLabel3.setText("categorias:");
        panelproducto.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, -1, 20));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/shipping_products_22121.png"))); // NOI18N
        panelproducto.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 80, 70));

        cmbcategorias.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Platos", "Bebidas", "Postres" }));
        cmbcategorias.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbcategoriasItemStateChanged(evt);
            }
        });
        cmbcategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbcategoriasActionPerformed(evt);
            }
        });
        cmbcategorias.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cmbcategoriasFocusGained(evt);
            }
        });
        panelproducto.add(cmbcategorias, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, 218, -1));

        tblproducto.setBackground(new java.awt.Color(204, 255, 255));
        tblproducto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 0), 2, true));
        tblproducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "IdProducto", "Nombre", "Precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblproducto.setToolTipText("Productos");
        jScrollPane1.setViewportView(tblproducto);

        panelproducto.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 560, 90));

        btnnuevo.setBackground(new java.awt.Color(102, 255, 102));
        btnnuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/agregar.png"))); // NOI18N
        btnnuevo.setText("Nuevo");
        btnnuevo.setBorder(null);
        btnnuevo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnnuevoMouseMoved(evt);
            }
        });
        btnnuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnnuevoMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnnuevoMouseEntered(evt);
            }
        });
        btnnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnuevoActionPerformed(evt);
            }
        });
        panelproducto.add(btnnuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 140, 40));

        btnmodificar.setBackground(new java.awt.Color(102, 255, 102));
        btnmodificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/modificar.png"))); // NOI18N
        btnmodificar.setText("Modificar");
        btnmodificar.setBorder(null);
        btnmodificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnmodificarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnmodificarMouseExited(evt);
            }
        });
        btnmodificar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnmodificarMouseMoved(evt);
            }
        });
        btnmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodificarActionPerformed(evt);
            }
        });
        panelproducto.add(btnmodificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, 160, 40));

        btneliminar.setBackground(new java.awt.Color(102, 255, 102));
        btneliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/delete.png"))); // NOI18N
        btneliminar.setText("Eliminar");
        btneliminar.setBorder(null);
        btneliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btneliminarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btneliminarMouseExited(evt);
            }
        });
        btneliminar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btneliminarMouseMoved(evt);
            }
        });
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });
        panelproducto.add(btneliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 270, 110, 40));

        btnsalir.setBackground(new java.awt.Color(102, 255, 102));
        btnsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1486564399-close_81512.png"))); // NOI18N
        btnsalir.setText("Salir");
        btnsalir.setBorder(null);
        btnsalir.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnsalirMouseMoved(evt);
            }
        });
        btnsalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnsalirMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnsalirMouseEntered(evt);
            }
        });
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });
        panelproducto.add(btnsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 270, 120, 40));

        panelmodificar.setBackground(new java.awt.Color(0, 0, 0));
        panelmodificar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Modificar Producto");
        panelmodificar.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, 210, 40));

        txtid.setEditable(false);
        panelmodificar.add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, 180, -1));

        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("IdProducto");
        panelmodificar.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 110, 30));

        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("Nombre");
        panelmodificar.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, 70, 20));

        txtnombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnombreKeyTyped(evt);
            }
        });
        panelmodificar.add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, 180, -1));

        btnguardar.setText("Guardar");
        btnguardar.setToolTipText("Guardar");
        btnguardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnguardarMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnguardarMouseEntered(evt);
            }
        });
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });
        panelmodificar.add(btnguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, -1, -1));

        btndescartar.setText("Descartar");
        btndescartar.setToolTipText("Descartar");
        btndescartar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btndescartarMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btndescartarMouseEntered(evt);
            }
        });
        btndescartar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndescartarActionPerformed(evt);
            }
        });
        panelmodificar.add(btndescartar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 260, -1, -1));

        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("Precio");
        panelmodificar.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 80, 20));

        txtprecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtprecioKeyTyped(evt);
            }
        });
        panelmodificar.add(txtprecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, 180, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelproducto, javax.swing.GroupLayout.PREFERRED_SIZE, 931, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelmodificar, javax.swing.GroupLayout.DEFAULT_SIZE, 931, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelproducto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelmodificar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbcategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbcategoriasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbcategoriasActionPerformed

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
  
        this.dispose();
    }//GEN-LAST:event_btnsalirActionPerformed

    private void btnsalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsalirMouseEntered
        // TODO add your handling code here:
         btnsalir.setBackground(new Color(0,204,51));//cambia el color del boton cuando paso el puntero sobre el boton
    }//GEN-LAST:event_btnsalirMouseEntered

    private void btnsalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsalirMouseExited
        // TODO add your handling code here:
         btnsalir.setBackground(new Color(102,255,102));//cambia el color del boton cuando paso el puntero sobre el boton
    }//GEN-LAST:event_btnsalirMouseExited

    private void btneliminarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btneliminarMouseEntered
        // TODO add your handling code here:
         btneliminar.setBackground(new Color(0,204,51));//cambia el color del boton cuando paso el puntero sobre el boton
    }//GEN-LAST:event_btneliminarMouseEntered

    private void btneliminarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btneliminarMouseExited
        // TODO add your handling code here:
         btneliminar.setBackground(new Color(102,255,102));//cambia el color del boton cuando paso el puntero sobre el boton
    }//GEN-LAST:event_btneliminarMouseExited

    private void btnmodificarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnmodificarMouseEntered
        // TODO add your handling code here:
         btnmodificar.setBackground(new Color(0,204,51));//cambia el color del boton cuando paso el puntero sobre el boton
    }//GEN-LAST:event_btnmodificarMouseEntered

    private void btnmodificarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnmodificarMouseExited
        // TODO add your handling code here:
         btnmodificar.setBackground(new Color(102,255,102));//cambia el color del boton cuando paso el puntero sobre el boton
    }//GEN-LAST:event_btnmodificarMouseExited

    private void btnnuevoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnnuevoMouseEntered
        // TODO add your handling code here:
         btnnuevo.setBackground(new Color(0,204,51));//cambia el color del boton cuando paso el puntero sobre el boton
    }//GEN-LAST:event_btnnuevoMouseEntered

    private void btnnuevoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnnuevoMouseExited
        // TODO add your handling code here:
         btnnuevo.setBackground(new Color(102,255,102));//cambia el color del boton cuando paso el puntero sobre el boton
    }//GEN-LAST:event_btnnuevoMouseExited

    private void btnnuevoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnnuevoMouseMoved
        // TODO add your handling code here:
        String texto="Nuevo";
        btnnuevo.setToolTipText(texto);//el metodo setToolTipTex hace que cuando pongo el puntero del raton sobre el boton muestre el nombre del boton
    }//GEN-LAST:event_btnnuevoMouseMoved

    private void btnmodificarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnmodificarMouseMoved
        // TODO add your handling code here:
        String texto="Modificar";
        btnmodificar.setToolTipText(texto);//el metodo setToolTipTex hace que cuando pongo el puntero del raton sobre el boton muestre el nombre del boton
    }//GEN-LAST:event_btnmodificarMouseMoved

    private void btneliminarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btneliminarMouseMoved
        // TODO add your handling code here:
        String texto="Eliminar";
        btneliminar.setToolTipText(texto);//el metodo setToolTipTex hace que cuando pongo el puntero del raton sobre el boton muestre el nombre del boton
    }//GEN-LAST:event_btneliminarMouseMoved

    private void btnsalirMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsalirMouseMoved
        // TODO add your handling code here:
        String texto="Salir";
        btnsalir.setToolTipText(texto);//el metodo setToolTipTex hace que cuando pongo el puntero del raton sobre el boton muestre el nombre del boton
    }//GEN-LAST:event_btnsalirMouseMoved

    private void cmbcategoriasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbcategoriasItemStateChanged
        // TODO add your handling code here:
       cmbcategorias.requestFocus();
        modeloProducto.setRowCount(0);
        seleccionado=String.valueOf(this.cmbcategorias.getSelectedIndex()+1);
        Producto(seleccionado); //invoque al método para llenar la tabla depende de lo que se escoja en el combobox
            
    }//GEN-LAST:event_cmbcategoriasItemStateChanged

    private void cmbcategoriasFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmbcategoriasFocusGained
        // TODO add your handling code here:
        modeloProducto.setRowCount(0);
        seleccionado=String.valueOf(this.cmbcategorias.getSelectedIndex()+1);
        Producto(seleccionado);
    }//GEN-LAST:event_cmbcategoriasFocusGained

    private void btnmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodificarActionPerformed
         if (tblproducto.getSelectedRow() != -1) //saber si esta seleccionada la fila en la tabla
        
        {
            txtid.setText(modeloProducto.getValueAt(tblproducto.getSelectedRow(), 0).toString());//mando la informacion de la fila a los txt donde se editara la informacion en este caso para el id
            txtnombre.setText(modeloProducto.getValueAt(tblproducto.getSelectedRow(), 1).toString());//mando la informacion de la fila a los txt donde se editara la informacion en este caso para el nombre
            txtprecio.setText(modeloProducto.getValueAt(tblproducto.getSelectedRow(),2).toString());
             panelproducto.setVisible(false);//deshabilita el panel donde esta tabla
              panelmodificar.setVisible(true);//habilita el panel donde estan los campos a modificar
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione un elemento para editar", null, JOptionPane.WARNING_MESSAGE);
         }
    }//GEN-LAST:event_btnmodificarActionPerformed

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed

        if (txtid.getText().equals("") || (txtprecio.getText().equals("") ||(txtnombre.getText().equals("")))) {
            JOptionPane.showMessageDialog(null, "Ingrese el nombre de la categoria", null, JOptionPane.WARNING_MESSAGE);
            txtnombre.requestFocus();
        } else {
            String id = txtid.getText();
            String nombre = txtnombre.getText();
            String precio=txtprecio.getText();
            productos.modificarproducto(id, nombre,precio);
            JOptionPane.showMessageDialog(null,"Modificacion exitosa");
            panelmodificar.setVisible(false);
            panelproducto.setVisible(true);
            ActualizarTabla();

        }

        
    }//GEN-LAST:event_btnguardarActionPerformed

    private void btndescartarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndescartarActionPerformed
        panelmodificar.setVisible(false);
        panelproducto.setVisible(true);
    }//GEN-LAST:event_btndescartarActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        if (tblproducto.getSelectedRow() != -1) //saber si esta seleccionada la fila en la tabla
 
        {
            txtid.setText(modeloProducto.getValueAt(tblproducto.getSelectedRow(), 0).toString());//mando la informacion de la fila a los txt donde se editara la informacion en este caso para el id
             String id = txtid.getText();
            productos.eliminar(id);
              cerrar();
           
           
            
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione un elemento para eliminar", null, JOptionPane.WARNING_MESSAGE);
         
        } 
      
    }//GEN-LAST:event_btneliminarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
    
    }//GEN-LAST:event_formWindowClosing

    private void btnnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuevoActionPerformed
       //a
    }//GEN-LAST:event_btnnuevoActionPerformed

    private void btnguardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnguardarMouseEntered
        // TODO add your handling code here:
        btnguardar.setBackground(new Color(0,204,51));//cambia el color del boton cuando paso el puntero sobre el boton
    }//GEN-LAST:event_btnguardarMouseEntered

    private void btndescartarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndescartarMouseEntered
        // TODO add your handling code here:
        btndescartar.setBackground(new Color(0,204,51));//cambia el color del boton cuando paso el puntero sobre el boton
    }//GEN-LAST:event_btndescartarMouseEntered

    private void btndescartarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndescartarMouseExited
        // TODO add your handling code here:
           btndescartar.setBackground(new Color(102,255,102));//cambia el color del boton cuando paso el puntero sobre el boton
    }//GEN-LAST:event_btndescartarMouseExited

    private void btnguardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnguardarMouseExited
        // TODO add your handling code here:
           btnguardar.setBackground(new Color(102,255,102));//cambia el color del boton cuando paso el puntero sobre el boton
    }//GEN-LAST:event_btnguardarMouseExited

    private void txtprecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtprecioKeyTyped
          char caracter = evt.getKeyChar();
        if (((caracter < '0') || (caracter > '9')) && (caracter != '.') && (caracter != '/') && (caracter != '-')) {
            evt.consume();
        } else if (((caracter > '0') || (caracter < '9'))) {
            evt.consume();
            txtprecio.setText(txtprecio.getText() + String.valueOf(caracter));
        }
    }//GEN-LAST:event_txtprecioKeyTyped

    private void txtnombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombreKeyTyped
        char caracter = evt.getKeyChar();
        if (Character.isLetter(caracter) || Character.isSpaceChar(caracter)) {
            evt.consume();
            txtnombre.setText(txtnombre.getText() + String.valueOf(caracter));
        } else if (!Character.isLetter(caracter) || !Character.isSpaceChar(caracter)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtnombreKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new productos().setVisible(true);
            }
        });
    }
    
    
    public void ActualizarTabla(){
          rs = null;
        rs = productos.llenarProductos(seleccionado);
        //modeloProducto.addColumn("IdCategorias");
        //modeloProducto.addColumn("nombre");
        String[] dato=new String[3]; 
        modeloProducto.setRowCount(0);//borra las filas 
        try {
            while (rs.next()) {
                dato[0]=rs.getString(1);
                dato[1]=rs.getString(2);
                dato[2]=rs.getString(3);
                modeloProducto.addRow(dato);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Error", 0);
        }
        tblproducto.setModel(modeloProducto);
  
         
       
    
    }
    
    public void cerrar(){
Object [] opciones ={"Aceptar","Cancelar"};
int eleccion = JOptionPane.showOptionDialog(rootPane,"En realidad desea borrar el dato","Mensaje de Confirmacion",
JOptionPane.YES_NO_OPTION,
JOptionPane.QUESTION_MESSAGE,null,opciones,"Aceptar");
if (eleccion == JOptionPane.YES_OPTION)
{
 ActualizarTabla();
 JOptionPane.showMessageDialog(null, "dato eliminado con exito ");
}else{
    JOptionPane.showMessageDialog(null, "cancelado", null, JOptionPane.WARNING_MESSAGE);
}}
  

    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndescartar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnmodificar;
    private javax.swing.JButton btnnuevo;
    private javax.swing.JButton btnsalir;
    private javax.swing.JComboBox<String> cmbcategorias;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelmodificar;
    private javax.swing.JPanel panelproducto;
    private javax.swing.JTable tblproducto;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtprecio;
    // End of variables declaration//GEN-END:variables
}
