
import estadisticas.EstadisticasProductos;
import estadisticas.ventasDiaria;
import java.awt.Color;
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author NERIO_H
 */
public class estadisticas_v extends javax.swing.JFrame {

    /**
     * Creates new form estadisticas_v
     */
    public estadisticas_v() {
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("/imagenes/imagenrestaurante.png")).getImage());
        this.setTitle("Estadisticas");
         this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnventamensual = new javax.swing.JButton();
        btnventadiaria = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnventamensual.setBackground(new java.awt.Color(102, 204, 102));
        btnventamensual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/monthlycalendar_112505 (1).png"))); // NOI18N
        btnventamensual.setText("Ventas Mensuales");
        btnventamensual.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnventamensualMouseMoved(evt);
            }
        });
        btnventamensual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnventamensualMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnventamensualMouseEntered(evt);
            }
        });
        btnventamensual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnventamensualActionPerformed(evt);
            }
        });
        jPanel1.add(btnventamensual, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, -1, 65));

        btnventadiaria.setBackground(new java.awt.Color(102, 204, 102));
        btnventadiaria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/dailycalendaronday1page_79519.png"))); // NOI18N
        btnventadiaria.setText("Ventas Diarias       ");
        btnventadiaria.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnventadiariaMouseMoved(evt);
            }
        });
        btnventadiaria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnventadiariaMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnventadiariaMouseEntered(evt);
            }
        });
        btnventadiaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnventadiariaActionPerformed(evt);
            }
        });
        jPanel1.add(btnventadiaria, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, -1, 65));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 0, 120));
        jLabel1.setText("Estadisticas de Ventas");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 200, 20));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 0, 120));
        jLabel2.setText("Seleccione una Opcion");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, -1, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnventamensualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnventamensualActionPerformed
        estadisticas.EstadisticasProductos nueva=new EstadisticasProductos();
        nueva.setVisible(true);
    }//GEN-LAST:event_btnventamensualActionPerformed

    private void btnventadiariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnventadiariaActionPerformed
       estadisticas.ventasDiaria nueva=new ventasDiaria();
        nueva.setVisible(true);
    }//GEN-LAST:event_btnventadiariaActionPerformed

    private void btnventamensualMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnventamensualMouseEntered
        // TODO add your handling code here:
        btnventamensual.setBackground(new Color(0,204,51));//cambia el color del boton cuando paso el puntero sobre el boton
    }//GEN-LAST:event_btnventamensualMouseEntered

    private void btnventamensualMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnventamensualMouseExited
        // TODO add your handling code here:
         btnventamensual.setBackground(new Color(102,204,102));//cambia el color del boton cuando paso el puntero sobre el boton
    }//GEN-LAST:event_btnventamensualMouseExited

    private void btnventadiariaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnventadiariaMouseEntered
        // TODO add your handling code here:
         btnventadiaria.setBackground(new Color(0,204,51));//cambia el color del boton cuando paso el puntero sobre el boton
    }//GEN-LAST:event_btnventadiariaMouseEntered

    private void btnventadiariaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnventadiariaMouseExited
        // TODO add your handling code here:
         btnventamensual.setBackground(new Color(102,204,102));//cambia el color del boton cuando paso el puntero sobre el boton
    }//GEN-LAST:event_btnventadiariaMouseExited

    private void btnventamensualMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnventamensualMouseMoved
        // TODO add your handling code here:
        String texto="Ventas Mensuales";
btnventamensual.setToolTipText(texto);//el metodo setToolTipTex hace que cuando pongo el puntero del raton sobre el boton muestre el nombre del boton
  
    }//GEN-LAST:event_btnventamensualMouseMoved

    private void btnventadiariaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnventadiariaMouseMoved
        // TODO add your handling code here:
        String texto="Ventas Diarias";
btnventadiaria.setToolTipText(texto);//el metodo setToolTipTex hace que cuando pongo el puntero del raton sobre el boton muestre el nombre del boton
  
    }//GEN-LAST:event_btnventadiariaMouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(estadisticas_v.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(estadisticas_v.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(estadisticas_v.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(estadisticas_v.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new estadisticas_v().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnventadiaria;
    private javax.swing.JButton btnventamensual;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
